trilitech/umami-v2

- src/components/AccountDrawer/AccountDrawerDisplay.test.tsx
- src/components/AccountDrawer/AccountDrawerDisplay.tsx
- src/components/AccountDrawer/AssetsPanel/AssetPanel.test.tsx
- src/components/AccountDrawer/AssetsPanel/DelegationDisplay.test.tsx
- src/components/AccountDrawer/AssetsPanel/NFTsGrid.tsx
- src/components/AccountDrawer/AssetsPanel/OperationListDisplay.test.tsx
- src/components/AccountDrawer/AssetsPanel/OperationListDisplay.tsx
- src/components/AccountDrawer/AssetsPanel/TokenList.tsx
- src/components/AccountDrawer/AssetsPanel/ViewAllLink.test.tsx
- src/components/AccountDrawer/AssetsPanel/ViewAllLink.tsx
- src/components/SendFlow/Undelegation/FormPage.tsx
Refactor tests related to account drawer.
[Task link](https://app.asana.com/0/1205770721172203/1206461299741932/f)
> Fix AccountDrawer tests

- src/views/home/AccountListWithDrawer.tsx
- src/views/nfts/NFTDrawerBody.tsx
- src/views/nfts/NFTDrawerCard.test.tsx
- src/views/nfts/NFTDrawerCard.tsx
- src/views/nfts/NftsView.tsx
[Task link](https://app.asana.com/0/1205770721172203/1206126507486405/f)
> Use NftWithOwner instead of NftBalance + owner pkh

- src/components/AccountDrawer/AccountDrawerDisplay.test.tsx
- src/components/AccountDrawer/index.tsx
- src/views/home/AccountListWithDrawer.tsx
[Task link](https://app.asana.com/0/1205770721172203/1206597776005791/f)
> Update name displayed in account drawer on rename

- src/components/AccountDrawer/AssetsPanel/NFTsGrid.tsx
- src/views/nfts/NFTCard.tsx
- src/views/nfts/NFTDrawerCard.tsx
[Task link](https://app.asana.com/0/1205770721172203/1206695783754835/f)
|  <img width="374" alt="Screenshot 2024-03-05 at 17 48 58" src="https://github.com/trilitech/umami-v2/assets/129749432/d6bb9a5b-5794-4da7-989c-c7dca44a1190">  | <img width="377" alt="Screenshot 2024-03-05 at 17 48 51" src="https://github.com/trilitech/umami-v2/assets/129749432/40c56fe7-8d13-4d8f-a42c-97853ad2b659">  |
> Put the amount of NFTs forward

- public/index.html
- src/index.css
- src/style/theme.ts
In design we use Inter everywhere
|   <img width="732" alt="Screenshot 2024-03-11 at 07 27 05" src="https://github.com/trilitech/umami-v2/assets/129749432/dae9e2fe-13fe-4943-9031-0e5a83a89f4d">   |   <img width="730" alt="Screenshot 2024-03-11 at 07 26 56" src="https://github.com/trilitech/umami-v2/assets/129749432/fcfb58fd-15f3-4339-b831-a8e723a001b3">  |
| <img width="480" alt="Screenshot 2024-03-11 at 07 28 34" src="https://github.com/trilitech/umami-v2/assets/129749432/f42a14cb-22d9-4e11-a27a-fdd785f0ee9a"> | <img width="397" alt="Screenshot 2024-03-11 at 07 28 51" src="https://github.com/trilitech/umami-v2/assets/129749432/33818d0d-5faf-429c-8c4a-b0382a26b415"> |
> Set Inter font as the main one

- src/WelcomeScreen.tsx
| <img width="638" alt="Screenshot 2024-03-17 at 15 02 24" src="https://github.com/trilitech/umami-v2/assets/129749432/dd4988b6-394f-4138-a3af-a45fd4f826bb">  |  <img width="630" alt="Screenshot 2024-03-17 at 15 02 17" src="https://github.com/trilitech/umami-v2/assets/129749432/7f2d563f-faec-452d-b178-fb65df81db40"> |
> Remove welcome screen transparent corners

- src/views/home/AccountListWithDrawer.tsx
- src/views/nfts/NftsView.tsx
- src/views/settings/DAppsDrawerCard.tsx
- src/views/settings/ErrorLogsDrawerCard.tsx
- src/views/settings/network/NetworkSettingsDrawerCard.tsx
It wasn't working when a drawer is open, but was when you had just a modal window open. Now both cases work. Most likely was broken due to a charka dependency update
> Fix autocomplete suggestions scrolling

- package.json
- src/components/AccountDrawer/AccountDrawerDisplay.test.tsx
- src/components/AccountDrawer/AssetsPanel/AssetsPanel.tsx
- src/index.tsx
- src/utils/useAssetsPolling.ts
- src/utils/useReactQueryOnError.ts
- src/views/operations/OperationsView.test.tsx
- src/views/operations/OperationsView.tsx
- src/views/operations/useGetOperations.test.tsx
- src/views/operations/useGetOperations.tsx
- yarn.lock
[Task link](https://app.asana.com/0/1205770721172203/1206805466258556/f)
- now we use already defined logic implemented by the react-query which simplifies the code quite much
- the data is sorted now (some tests started to fail because the IDs weren't sorted correctly)
- if you click the refresh button it will also trigger an update on the operations page (and the account drawer) too 
> Refactor operations fetching

- src/components/OperationTile/ContractCallTile.tsx
- src/components/OperationTile/DelegationTile.tsx
- src/components/OperationTile/Fee.tsx
- src/components/OperationTile/InternalPrefix.test.tsx
- src/components/OperationTile/InternalPrefix.tsx
- src/components/OperationTile/OperationTile.test.tsx
- src/components/OperationTile/OriginationTile.tsx
- src/components/OperationTile/TokenTransferTile.test.tsx
- src/components/OperationTile/TokenTransferTile.tsx
- src/components/OperationTile/TransactionTile.tsx
- src/components/OperationTile/testUtils.ts
- src/components/OperationTile/useGetOperationDestination.ts
- src/components/OperationTile/useShowAddress.test.tsx
- src/components/OperationTile/useShowAddress.tsx
- src/types/Transfer.ts
- src/utils/hooks/assetsHooks.ts
- src/utils/hooks/getAccountDataHooks.test.ts
- src/utils/hooks/getAccountDataHooks.ts
- src/utils/redux/slices/assetsSlice.ts
- src/utils/tezos/fetch.ts
- src/views/operations/useGetOperations.test.tsx
|  <img width="571" alt="Screenshot 2024-04-05 at 01 41 14" src="https://github.com/trilitech/umami-v2/assets/129749432/21f4f851-3b71-4343-b188-5feaf3cd8415"> |   <img width="574" alt="Screenshot 2024-04-05 at 01 00 17" src="https://github.com/trilitech/umami-v2/assets/129749432/6d54d503-5151-49f1-a990-f429a84493f2">  |
| <img width="571" alt="Screenshot 2024-04-05 at 01 41 18" src="https://github.com/trilitech/umami-v2/assets/129749432/851c57ce-ed5a-4927-8ec1-595ffcb443ac"> | <img width="571" alt="Screenshot 2024-04-05 at 01 00 24" src="https://github.com/trilitech/umami-v2/assets/129749432/4843c5a9-b462-4c87-9354-a7ec33079841"> |
> Mark internal operations

- src/mocks/factories.ts
- src/utils/hooks/multisigHooks.test.tsx
- src/utils/hooks/multisigHooks.ts
- src/utils/hooks/removeAccountDependenciesHooks.test.ts
- src/utils/hooks/removeAccountDependenciesHooks.ts
- src/utils/hooks/setAccountDataHooks.test.ts
- src/utils/hooks/setAccountDataHooks.ts
- src/utils/redux/slices/multisigsSlice.test.ts
- src/utils/redux/slices/multisigsSlice.ts
[Task link](https://app.asana.com/0/1205770721172203/1206776085221918/f)
> Delete multisigs on account deletion

- src/components/OperationTile/InternalPrefix.tsx
- src/components/OperationTile/TokenTransferTile.test.tsx
- src/components/OperationTile/TokenTransferTile.tsx
| <img width="755" alt="Screenshot 2024-04-10 at 12 16 28" src="https://github.com/trilitech/umami-v2/assets/129749432/512994f0-c57e-4df9-b119-f6adb65d07d7"> | <img width="668" alt="Screenshot 2024-04-10 at 12 17 40" src="https://github.com/trilitech/umami-v2/assets/129749432/8cf34f40-a153-482e-a3ba-183623436b33"> |
| <img width="490" alt="Screenshot 2024-04-10 at 12 20 03" src="https://github.com/trilitech/umami-v2/assets/129749432/36c2bedf-14c5-4a4e-ae86-13b3033cc208"> | <img width="561" alt="Screenshot 2024-04-10 at 12 19 52" src="https://github.com/trilitech/umami-v2/assets/129749432/9a057983-658f-41ac-97b5-bc59fd82bdaa"> |
> Fix internal prefix bugs

- src/components/AddressAutocomplete/AddressAutocomplete.tsx
- src/components/AddressAutocomplete/Suggestions.tsx
- src/components/AddressTile/AddressTile.test.tsx
- src/components/AddressTile/AddressTile.tsx
delegate -> click on the baker input
|  <img width="421" alt="Screenshot 2024-04-15 at 06 52 10" src="https://github.com/trilitech/umami-v2/assets/129749432/e1a44654-6732-4a74-8ffc-bd9ff75e8985"> | <img width="467" alt="Screenshot 2024-04-15 at 09 05 53" src="https://github.com/trilitech/umami-v2/assets/129749432/fc636a78-6400-4e0f-a0d9-70a0f73c9b3e"> |
other autocompletes remain untouched
> Fix baker suggestions elements alignment

- .github/workflows/e2e.yaml
- cucumber.cjs
- docker-compose.yaml
- nginx.conf
- src/e2e/steps/hooks.ts
- src/e2e/utils.ts
It is better maintained than flextesa
> Migrate to tezbox image

- src/utils/beacon/PermissionRequestModal.tsx
It would stay open even after sign
> Close beacon permission request modal on sign

- src/components/SendFlow/MultisigAccount/SignTransactionFormPage.tsx
[Task link]()
| ![image](https://github.com/trilitech/umami-v2/assets/169451151/2df6433b-07b0-4737-bf74-a7d0d6db9c67)  | <img width="503" alt="image" src="https://github.com/trilitech/umami-v2/assets/169451151/c6504e3b-34b4-4743-ae4b-dbef36d1139c">  |
> Multisig modal ui fix

- src/utils/beacon/PermissionRequestModal.test.tsx
- src/utils/beacon/PermissionRequestModal.tsx
- src/utils/beacon/SignPayloadRequestModal.test.tsx
- src/utils/beacon/SignPayloadRequestModal.tsx
- src/utils/beacon/decodePayload.test.ts
- src/utils/beacon/decodePayload.ts
[Task link](https://app.asana.com/0/1205770721172203/1206727614749706/f)
|<img width="534" alt="image" src="https://github.com/trilitech/umami-v2/assets/169451151/0b179a5e-1ef0-4a83-b453-8918e05b45ab">|![image](https://github.com/trilitech/umami-v2/assets/169451151/d161ecd1-f0a8-4001-a538-1a64e664c34e)|
> Parse beacon payload

- src/components/AdvancedSettingsAccordion.tsx
- src/utils/format.ts
- src/utils/hooks/assetsHooks.ts
it's always a BigNumber unless the provided value is a NaN https://github.com/ecadlabs/taquito/blob/master/packages/taquito-utils/src/format.ts#L27
> Fix mutezToTez type

- apps/web/package.json
- apps/web/src/App.tsx
- apps/web/src/main.tsx
- yarn.lock
[Task link](https://app.asana.com/0/1207041888417083/1207650864030742/f)
> Web add data polling

- vercel.json
This PR enables routing using vercel deployment
> Make vercel understand different paths

- apps/desktop/src/components/OperationTile/OriginationTile.test.tsx
- apps/desktop/src/components/OperationTile/OriginationTile.tsx
- packages/tzkt/src/types.ts
> Fix failed origination tile rendering

- packages/components/src/DynamicModal/DynamicModal.tsx
> Fix @umami/components tests

- apps/web/src/components/AddressPill/AddressPill.stories.tsx
- apps/web/src/components/AddressPill/AddressPill.tsx
https://github.com/user-attachments/assets/6b385eb5-1e7b-413b-8f26-6e62f7750962
> [Web] Apply styling to AddressPill

- apps/embed-iframe/package.json
- apps/embed-iframe/src/ClientsPermissions.ts
- apps/embed-iframe/src/EmbedAppContext.tsx
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/SignOperationModalContent.tsx
- apps/embed-iframe/src/loginModalHooks.tsx
- apps/embed-iframe/src/main.tsx
- apps/embed-iframe/src/signOperationModalHooks.tsx
- apps/embed-iframe/src/utils.ts
- yarn.lock
[Task link](https://app.asana.com/0/1207646563234653/1207667419666416/f)
- Flatten `UserData` type
- Save `network` & `userData` on login to local storage
- Check for saved user data and send it to component on `init()`
- Remove permission checks for ghostnet
- Add context for sharing data between components
Tested manually.
> Integrate embed to kanvas

- apps/embed-iframe/package.json
- apps/embed-iframe/src/EmbedAppContext.tsx
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- yarn.lock
- Iframe now handles `setConfig` message
- Network is set up at `setConfig`, not at `login`
- Login Options can now be customized from the config
- If login type of saved userData is not in config login options, user will be logged out
Tested manually
[Task link](https://app.asana.com/0/1207646563234653/1207667420031338/f)
> Handle embed iframe config

- apps/web/package.json
- apps/web/src/Layout.tsx
- apps/web/src/components/Main/Main.tsx
- apps/web/src/components/Navbar/Navbar.tsx
- apps/web/src/components/OperationTile/OperationTileView.tsx
- apps/web/src/index.scss
- apps/web/src/providers/UmamiTheme.tsx
- apps/web/src/styles/theme.ts
- yarn.lock
[Task link](https://app.asana.com/0/1206413667831253/1207764629353041/f)
> Improve activity UI

- apps/web/src/Layout.tsx
- apps/web/src/components/Main/Main.tsx
- apps/web/src/components/Navbar/Navbar.tsx
- apps/web/src/index.scss
[Task link](https://app.asana.com/0/1207041888417083/1207882654304324/f)
Also, I fixed the footer margin for mobile & now the layout is defined only for mobile and large screens (no intermediary one which isn't defined)
|  <img width="1096" alt="Screenshot 2024-07-29 at 09 58 28" src="https://github.com/user-attachments/assets/e98bd370-ab39-42db-97e0-3ecba7452d6a"> |  <img width="1125" alt="Screenshot 2024-07-29 at 14 42 32" src="https://github.com/user-attachments/assets/f28ca3b2-602e-4661-8f52-08764c0db500">  |
> Rearrange tabs

- apps/embed-iframe/src/EmbedAppContext.tsx
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/LoginModalContext.tsx
- apps/embed-iframe/src/loginModalHooks.tsx
- apps/embed-iframe/src/main.tsx
[Task link](https://app.asana.com/0/1207646563234653/1207796956748999/f)
https://github.com/user-attachments/assets/69155fb9-281e-48e6-a99a-e14f21837f85
> Remove embed login modal for single login option

- apps/embed-iframe/src/ClientsPermissions.ts
Kanvas url is whitelisted in order for the demo to work on mainnet.
[Task link](https://app.asana.com/0/1207646563234653/1207667419666416/f)
> [embed] Add kanvas to umami-embed whitelist

- apps/desktop/src/components/Onboarding/connectOrCreate/useOnboardWithSocial.tsx
- apps/embed-iframe/src/ClientsPermissions.ts
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/imported/style/useColor.ts
- apps/web/src/components/Onboarding/connectOrCreate/useOnboardWithSocial.tsx
- packages/social-auth/src/Auth.test.ts
- packages/social-auth/src/Auth.ts
[Task link](https://app.asana.com/0/1207646563234653/1207749664422716/f)
[Kukai way of handling data](https://github.com/kukai-wallet/kukai/blob/3ebc2bc040edbaf7783fd4224c098223e6af4d75/src/app/services/torus/torus.service.ts#L215)
Depends on [umami-embed change](https://github.com/trilitech/umami-embed-npm/pull/10)
- emailAddress: `email.coogle.com`
- id: `email.coogle.com`
- imageUrl: `google avatar url`
- name: `Name Surname`
- typeOfLogin: `google`
- emailAddress: `undefined`
- id: `reddit username`
- imageUrl: `reddit avatar`
- name: `reddit username`
- typeOfLogin: `reddit`
- emailAddress: `undefined`
- id: `twitter id`
- imageUrl: `twitter avatar`
- name: `Name Surname`
- typeOfLogin: `twitter`
- emailAddress: `test@email.com`
- id: `facebook id`
- imageUrl: `facebook avatar`
- …
> Provide more user data in embed

- apps/embed-iframe/package.json
- apps/embed-iframe/src/EmbedAppContext.tsx
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginButtonComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/utils.ts
- yarn.lock
> Bump @trilitech-umami/umami-embed to the last version

- apps/web/src/components/TabSwitch/TabSwitch.stories.tsx
- apps/web/src/components/TabSwitch/TabSwitch.test.tsx
- apps/web/src/components/TabSwitch/TabSwitch.tsx
- apps/web/src/styles/theme.ts
open storybook
https://github.com/user-attachments/assets/24610b27-9b5f-468d-b5bd-5436519b16ab
> Web add mobile tab switch

- apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx
- apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx
- apps/web/src/components/AccountSelectorModal/RemoveAccountModal.tsx
- apps/web/src/components/ActionsDropdown/ActionsDropdown.tsx
- apps/web/src/components/ActionsDropdown/index.ts
- apps/web/src/components/Header/Actions.tsx
- apps/web/src/components/Menu/EditNetworkMenu.test.tsx
- apps/web/src/components/Menu/EditNetworkMenu.tsx
- apps/web/src/components/Menu/ImportBackupModal.tsx
- apps/web/src/components/Menu/NetworkMenu.test.tsx
- apps/web/src/components/Menu/NetworkMenu.tsx
- apps/web/src/components/Onboarding/FakeAccount.tsx
- apps/web/src/components/Onboarding/derivationPath/DerivationPath.tsx
- apps/web/src/components/Onboarding/nameAccount/NameAccountDisplay.tsx
- apps/web/src/components/Onboarding/restoreBackupFile/RestoreBackupFile.tsx
- apps/web/src/components/Onboarding/restoreLedger/RestoreLedger.tsx
- apps/web/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.tsx
- apps/web/src/components/Onboarding/verifySeedphrase/VerifySeedphrase.tsx
- apps/web/src/components/SendFlow/utils.tsx
- apps/web/src/components/beacon/PermissionRequestModal.tsx
- apps/web/src/styles/theme.ts
[Task link](https://app.asana.com/0/1207041888417083/1207811126378425/f)
https://github.com/user-attachments/assets/2818053a-909e-4a04-b119-67d99a91477f
> Add network settings

- apps/embed-iframe/src/LoginButtonComponent.tsx
- apps/embed-iframe/src/imported/style/theme.ts
Tasks:
- [Modals on mobile should touch the bottom on the screen](https://app.asana.com/0/1207646563234653/1207911342319026/f)
- [Shadows around socila icon should be lighter](https://app.asana.com/0/1207646563234653/1207984432839197/f)
Figma: https://www.figma.com/design/kUJJ7T75lP4GPNMg4GMVt1/Web-%26-Embed?node-id=783-50301&t=BTlrbEwbEfKTkoXG-0
|   <img width="676" alt="Screenshot 2024-08-15 at 13 12 55" src="https://github.com/user-attachments/assets/1e7bb498-3a04-462f-bfa2-663d85410860">     |   <img width="894" alt="Screenshot 2024-08-15 at 13 10 37" src="https://github.com/user-attachments/assets/14e7b874-7135-47ef-a15c-dc7332273dbf">  |
|     <img width="609" alt="Screenshot 2024-08-15 at 13 13 01" …
> Small fixes for Embed UI

- apps/web/src/components/BackButton/BaseBackButton.tsx
- apps/web/src/components/CloseButton/BaseCloseButton.tsx
- apps/web/src/components/SendFlow/SignPageHeader.tsx
- apps/web/src/styles/theme.ts
- apps/web/src/views/NFTs/NFTDrawerCard/JSONAccordion.tsx
- apps/web/src/views/NFTs/NFTDrawerCard/NFTDrawerCard.tsx
- apps/web/src/views/NFTs/NFTDrawerCard/TagsSection.tsx
- apps/web/src/views/NFTs/NFTFilter/NFTFilter.tsx
- apps/web/src/views/NFTs/NFTs.tsx
[Task link](https://app.asana.com/0/1205763124050853/1207650864030726/f)
[Task link](https://app.asana.com/0/1207041888417083/1207650864030725/f)
> Address NFT UI feedback

- apps/web/src/components/Menu/AddressBookMenu/EditContactMenu.tsx
- apps/web/src/views/Tokens/Token.tsx
This small pr refactors submit action in `EditContactMenu` component
> Refactor EditContactMenu submit

- apps/web/src/components/SendFlow/Delegation/SignPage.tsx
- apps/web/src/components/SendFlow/FinalizeUnstake/SignPage.tsx
- apps/web/src/components/SendFlow/NFT/FormPage.test.tsx
- apps/web/src/components/SendFlow/NFT/FormPage.tsx
- apps/web/src/components/SendFlow/NFT/SignPage.test.tsx
- apps/web/src/components/SendFlow/NFT/SignPage.tsx
- apps/web/src/components/SendFlow/SignPageHeader.tsx
- apps/web/src/components/SendFlow/Stake/SignPage.tsx
- apps/web/src/components/SendFlow/Tez/SignPage.tsx
- apps/web/src/components/SendFlow/Token/SignPage.tsx
- apps/web/src/components/SendFlow/Undelegation/SignPage.tsx
- apps/web/src/components/SendFlow/Unstake/SignPage.tsx
- apps/web/src/components/SendFlow/onSubmitFormActionHooks.tsx
- apps/web/src/components/SendFlow/utils.tsx
- packages/components/src/DynamicDisclosure/DynamicDisclosure.tsx
- packages/components/src/DynamicDisclosure/index.ts
- packages/components/src/DynamicDisclosure/useMultiForm.test.tsx
- packages/components/src/DynamicDisclosure/useMultiForm.tsx
- packages/components/src/testUtils.tsx
This thing allows to have multi page forms with a proper goBack behaviour
> Add support for multi page form re-fill on go back

- apps/embed-iframe/index.html
- apps/embed-iframe/package.json
- apps/embed-iframe/src/EmbedAppContext.tsx
- apps/embed-iframe/src/EmbeddedComponent.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/loginModalHooks.tsx
- apps/embed-iframe/src/main.tsx
- yarn.lock
[Task link](https://app.asana.com/0/1207646563234653/1207972978356852/f)
[Design Doc](https://docs.google.com/document/d/18VHGwjt1sBzn9Gb8FdKhBkGCxmmuZ7BWfGOMCFNreoI/edit?usp=sharing)
[Data Format Description](https://www.notion.so/tezosfoundation/Analytics-for-Umami-374af98bcb284b53af4d1f89c3132d35)
> Add Vercel Analytics to embed iframe

- apps/desktop/src/components/Onboarding/connectOrCreate/useOnboardWithSocial.tsx
- apps/desktop/src/components/SendFlow/SignButton.tsx
- apps/embed-iframe/src/LoginModalContent.tsx
- apps/embed-iframe/src/SignOperationModalContent.tsx
- apps/oauth/public/redirect.html
- apps/web/src/components/Onboarding/connectOrCreate/useOnboardWithSocial.tsx
- apps/web/src/components/SendFlow/SignButton.tsx
- packages/social-auth/src/Auth.test.ts
- packages/social-auth/src/Auth.ts
- packages/social-auth/src/forIDP.test.ts
- packages/social-auth/src/forIDP.ts
- packages/social-auth/src/types.ts
this allows us to have social login through custom domains (which we use for vercel previews)
> Allow custom embed & web domains in auth

- apps/desktop/src/utils/beacon/useHandleBeaconMessage.test.tsx
- apps/desktop/src/utils/beacon/useHandleBeaconMessage.tsx
- apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx
- apps/web/src/components/beacon/useHandleBeaconMessage.tsx
- packages/core/package.json
- packages/core/src/beaconUtils.test.ts
- packages/core/src/beaconUtils.ts
- packages/core/src/index.ts
- pnpm-lock.yaml
[Task link](https://app.asana.com/0/1207646563234653/1207893606950568/f)
Prep for https://github.com/trilitech/umami-v2/pull/1644
> Add shared beacon utils

- apps/embed-iframe/package.json
https://vercel.com/docs/deployments/configure-a-build#corepack
> [embed] Set pnpm as package manager fro embed-iframe

- apps/web/src/components/Onboarding/connectOrCreate/ConnectOrCreate.tsx
- apps/web/src/styles/theme.ts
- apps/web/src/views/Welcome/OnboardWithEmailButton.tsx
- apps/web/src/views/Welcome/OnboardWithFacebookButton.tsx
- apps/web/src/views/Welcome/OnboardWithGoogleButton.tsx
- apps/web/src/views/Welcome/OnboardWithRedditButton.tsx
- apps/web/src/views/Welcome/OnboardWithTwitterButton.tsx
- apps/web/src/views/Welcome/Welcome.tsx
- apps/web/src/views/Welcome/useOnboardWithSocial.tsx
> Add social auth for web

- apps/desktop/src/components/Onboarding/restoreSecretKey/RestoreSecretKey.tsx
- apps/web/src/components/AccountTile/AccountTileIcon.tsx
- apps/web/src/components/Onboarding/ImportWallet/ImportWallet.tsx
- apps/web/src/components/Onboarding/ImportWallet/SecretKeyTab.test.tsx
- apps/web/src/components/Onboarding/ImportWallet/SecretKeyTab.tsx
- apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTabPanel.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.test.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.tsx
- apps/web/src/components/Onboarding/restoreSecretKey/RestoreSecretKey.tsx
- packages/tezos/src/helpers.test.ts
- packages/tezos/src/helpers.ts
[Task link](https://app.asana.com/0/1207041888417083/1207985676541268/f)
> Add secret key onboarding page

- packages/multisig/src/fetch.test.ts
- packages/multisig/src/fetch.ts
- packages/multisig/src/helpers.test.ts
- packages/multisig/src/types.ts
Now we fetch all the multisigs so that we don't miss any of the existing ones
> Improve multisig account fetching

- apps/desktop/public/electron.js
It previously it'd open the `/` path which was prohibited. now it's being replaced with the index.html file instead
> Fix desktop offboarding

- apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.test.tsx
- apps/web/src/components/Menu/AdvancedMenu/AdvancedMenu.test.tsx
- apps/web/src/components/Menu/Menu.test.tsx
- apps/web/src/components/NameAccountModal/NameAccountModal.test.tsx
- apps/web/src/components/NameAccountModal/NameAccountModal.tsx
- apps/web/src/components/Onboarding/AdvancedAccountSettings/AdvancedAccountSettings.tsx
- apps/web/src/components/Onboarding/OnboardOptions/OnboardOptions.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.test.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.tsx
- apps/web/src/components/Onboarding/VerificationFlow/useIsAccountVerified.test.tsx
- apps/web/src/components/Onboarding/VerificationFlow/useIsAccountVerified.tsx
- apps/web/src/styles/colors.ts
- apps/web/src/styles/theme.ts
[Task link](https://app.asana.com/0/1207041888417083/1208254818962954/f)
https://github.com/user-attachments/assets/a1aaf6b6-c8c1-47d7-bc88-2f47a1e95e72
> Add "Create a new wallet" flow when click on "Add Account" button

- packages/data-polling/.eslintrc.cjs
- packages/data-polling/src/useDataPolling.ts
- packages/data-polling/src/useReactQueryErrorHandler.ts
- packages/multisig/.eslintrc.cjs
- packages/multisig/src/helpers.ts
- packages/multisig/src/types.ts
[Task link](https://app.asana.com/0/1207041888417083/1208292322554144/f)
**Before**
https://github.com/user-attachments/assets/247f63b8-3463-434d-b6b2-37c644ca4845
**Now**
https://github.com/user-attachments/assets/83fbe388-cec5-4e36-ab7f-f0761c432ec8
> Fix issues when changing the network

- apps/web/src/components/AddressAutocomplete/KnownAccountsAutocomplete.tsx
- apps/web/src/components/Header/Header.tsx
[Task link](https://app.asana.com/0/1207041888417083/1208292322554149/f)
> Remove multisig accounts from recipients list

- apps/embed-iframe/src/SignPayloadModalContent.tsx
Fix after this change: https://github.com/trilitech/umami-v2/pull/1913
> [embed] Fix decodeBeaconPayload call

- apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx
- apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.test.tsx
- apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.tsx
- apps/web/src/components/Onboarding/SetupPassword/types.ts
- apps/web/src/components/Onboarding/SetupPassword/useGetSetupPasswordSubmitHandler.tsx
- packages/state/src/hooks/setAccountData.ts
[Task link](https://app.asana.com/0/1207041888417083/1208327359272028/f)
> User should switch immediately to a new added account

- apps/desktop/src/utils/beacon/PermissionRequestModal.tsx
- apps/web/src/components/beacon/PermissionRequestModal.tsx
- apps/web/src/styles/theme.ts
[Task link](https://github.com/trilitech/umami-security-review/issues/19)
| Web | Desktop |
|<img width="529" alt="image" src="https://github.com/user-attachments/assets/29586762-dea0-4b7a-bebf-a316d61e58e8">|<img width="530" alt="image" src="https://github.com/user-attachments/assets/b94d082d-59b7-4a30-8f8f-70c846f0fa7e">|
> Add report button to dapp request modal

- apps/web/src/components/MnemonicWord/MnemonicWord.tsx
- apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTab.tsx
- apps/web/src/components/TabSwitch/TabSwitch.tsx
- apps/web/src/styles/theme.ts
> Fix UI bugs

- apps/web/src/components/Menu/DrawerContentWrapper.tsx
- packages/components/src/utils/validationSchemes.test.ts
- packages/components/src/utils/validationSchemes.ts
[Task link](https://github.com/trilitech/umami-security-review/issues/25#issuecomment-2441623219)
|![image](https://github.com/user-attachments/assets/65486829-d162-4f19-9e75-735f042a9f8c)|<img width="527" alt="image" src="https://github.com/user-attachments/assets/ac3fe42c-abe1-47a5-b608-11e8b40a0670">|
> Fix network url regex

- apps/desktop/public/electron.js
Previously it'd get stuck on the last stage. Also, mail woudn't work anyway
> Fix desktop social auth

- apps/embed-iframe-mainnet/vercel.json
To match networks we use: 
```
export const MAINNET: Network = {
name: "mainnet",
rpcUrl: "https://prod.tcinfra.net/rpc/mainnet/",
tzktApiUrl: "https://api.mainnet.tzkt.io",
tzktExplorerUrl: "https://tzkt.io",
buyTezUrl: "https://widget.wert.io",
};
export const GHOSTNET: Network = {
name: "ghostnet",
rpcUrl: "https://ghostnet.ecadinfra.com",
tzktApiUrl: "https://api.ghostnet.tzkt.io",
tzktExplorerUrl: "https://ghostnet.tzkt.io",
buyTezUrl: "https://faucet.ghostnet.teztnets.com/",
};
```
> Fix CSP for embed-iframe-mainnet

- apps/desktop/package.json
> Bump desktop version to 2.3.4

- .github/workflows/release.yaml
- apps/desktop/package.json
This PR adds mac release workflow
> Add mac release workflow

- apps/web/src/components/SecurityWarningModal/SecurityWarningModal.test.tsx
- apps/web/src/components/SecurityWarningModal/SecurityWarningModal.tsx
This PR adds checkbox to SecurityWarningModal
> Update SecurityWarningModal ui

- apps/desktop/src/assets/icons/Eye.tsx
- apps/desktop/src/assets/icons/EyeSlash.tsx
- apps/desktop/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.test.tsx
- apps/desktop/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.tsx
- apps/desktop/src/components/Onboarding/verifySeedphrase/VerifySeedphrase.test.tsx
- apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTab.test.tsx
- apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTab.tsx
- apps/web/src/components/Onboarding/VerificationFlow/VerifySeedphraseModal.test.tsx
- apps/web/src/components/Onboarding/VerificationFlow/VerifySeedphraseModal.tsx
- apps/web/src/styles/theme.ts
- packages/components/src/components/MnemonicAutocomplete/MnemonicAutocomplete.test.tsx
- packages/components/src/components/MnemonicAutocomplete/MnemonicAutocomplete.tsx
[Task link](https://github.com/trilitech/umami-security-review/issues/41)
|<img width="595" alt="image" src="https://github.com/user-attachments/assets/1f0f7e56-3977-4cfb-af68-db1c16ba3691">|<img width="626" alt="image" src="https://github.com/user-attachments/assets/f68b6fb8-4fe5-4c16-ba69-3ec90c59178f">|
|<img width="512" alt="image" src="https://github.com/user-attachments/assets/631ac2e8-de10-4c4c-979c-70a13b0f5367">|<img width="530" alt="image" src="https://github.com/user-attachments/assets/576c6284-253e-44f5-bd7f-b5960e397ce5">|
> Hide mnemonic during input

- apps/desktop-e2e/src/steps/onboarding.ts
- apps/desktop/public/electron.js
- apps/desktop/public/preload.js
- apps/desktop/src/components/Onboarding/notice/Notice.tsx
- apps/desktop/src/components/Onboarding/showSeedphrase/ShowSeedphrase.test.tsx
- apps/desktop/src/components/Onboarding/showSeedphrase/ShowSeedphrase.tsx
- apps/desktop/src/global.d.ts
- apps/web/src/components/CopyButton/CopyButton.tsx
- apps/web/src/components/MnemonicWord/MnemonicWord.tsx
- apps/web/src/components/Onboarding/VerificationFlow/RecordSeedphraseModal.tsx
- packages/state/src/hooks/useAsyncActionHandler.ts
This PR adds copy mnemonic button to desktop and mnemonic reveal logic to Seed Phrase Record step
> Add reveal mnemonic logic

- packages/state/src/hooks/useAsyncActionHandler.test.ts
- packages/state/src/hooks/useAsyncActionHandler.ts
handleAsyncActionUnsafe will not show a toast twice and register the same event twice in the log.
```
cd packages/state
pnpm run test src/hooks/useAsyncActionHandler.test.ts
```
Run nested `useAsyncActionHandler`. E.g. take [PR#2029](https://github.com/trilitech/umami-v2/pull/2029) and check that toast is shown just once with that PR.
Then use https://taquito-test-dapp.pages.dev/ to run test "Contract call fails".
| 
| 
|
> fix: avoid double toast by handleAsyncActionUnsafe

- apps/desktop/package.json
Bumps desktop version to 2.3.6
> Bump desktop version to 2.3.6

- apps/web/src/components/WalletConnect/SessionProposalModal.tsx
Added Beta warning for WalletConnect connection proposal modal
> feat: WalletConnect Beta warning

- packages/state/src/hooks/network.ts
Wert link for mainnet shows BTC & EUR, should be XTZ & USD
[Task link](https://www.notion.so/tezosfoundation/Tokens-Tab-FTU-177b402b7f6080dd8e2acb250b94cf50?pvs=4)
> [WEB] Fix buyTezLink on mainnet 

- apps/web/src/components/SendFlow/common/ContractCallSignPage.tsx
- apps/web/src/components/SendFlow/common/DelegationSignPage.tsx
- apps/web/src/components/SendFlow/common/FinalizeUnstakeSignPage.tsx
- apps/web/src/components/SendFlow/common/Header.tsx
- apps/web/src/components/SendFlow/common/OriginationOperationSignPage.test.tsx
- apps/web/src/components/SendFlow/common/OriginationOperationSignPage.tsx
- apps/web/src/components/SendFlow/common/SingleSignPage.test.tsx
- apps/web/src/components/SendFlow/common/StakeSignPage.tsx
- apps/web/src/components/SendFlow/common/TezSignPage.tsx
- apps/web/src/components/SendFlow/common/UndelegationSignPage.tsx
- apps/web/src/components/SendFlow/common/UnstakeSignPage.tsx
- apps/web/src/components/Titles/Titles.tsx
- apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx
- apps/web/src/components/common/SignPayloadRequestModal.test.tsx
- apps/web/src/components/common/SignPayloadRequestModal.tsx
Aligned titles in all requests. These modals are used for both Beacon and WalletConnect.
Asana: [task](https://app.asana.com/0/1205770721172203/1209120233875447).
1. Connect https://taquito-test-dapp.pages.dev/
2. Send different requests
|Title| Before | Now |
| ------ | ------ | --- |
| Sign Payload Request | <img width="517" alt="image" src="https://github.com/user-attachments/assets/32740871-1493-4ff4-9782-12da5f25ca90" /> | <img width="517" alt="image" src="https://github.com/user-attachments/assets/9184c5ae-664d-4f07-8aef-4710eb2a7c1d" />|
| Send Request | <img width="517" alt="image" src="https://github.com/user-attachments/assets/3f51cecb-ca4b-4d5c-b474-33bc5df81118" /> | <img width="517" alt="image" …
> fix: UI - aligned request titles

- apps/web/src/components/SendFlow/SuccessStep.test.tsx
- apps/web/src/components/SendFlow/SuccessStep.tsx
[UMA-1147](https://linear.app/tezos/issue/UMA-1147) Success Text corrupted on tx confirmation
Fixed. Added tests.
Perform any successful transaction.
| <img width="390" alt="image" src="https://github.com/user-attachments/assets/ac87e6d6-435b-4424-920b-18173b75393a" /> | <img width="390" alt="image" src="https://github.com/user-attachments/assets/63254466-f107-4d1a-b755-767942e665ae" /> |
> fix: corrupted Success text

- apps/web/src/components/AccountCard/AccountButtons.test.tsx
- apps/web/src/components/AccountCard/SendTezButton.tsx
- apps/web/src/components/ConfirmationModal/ConfirmationModal.tsx
- apps/web/src/components/SendFlow/InsufficientFunds/InsufficientFunds.tsx
- apps/web/src/components/SendFlow/InsufficientFunds/index.ts
- apps/web/src/components/SendFlow/Tez/FormPage.test.tsx
- apps/web/src/components/SendFlow/Tez/FormPage.tsx
[Task link](https://linear.app/tezos/issue/UMA-1075/send-xtz-when-i-have-no-xtz-i-can-still-type-in-an-amount-select-a)
> [Web][UMA-1075] Add insufficient funds modal

- apps/desktop/jest.config.ts
- apps/web/jest.config.ts
- packages/components/jest.config.ts
- packages/data-polling/jest.config.ts
- packages/state/jest.config.ts
- packages/state/package.json
- packages/state/src/reducer.ts
- packages/state/src/utils/localEncryptionKey.ts
- pnpm-lock.yaml
Encrypt localstorage with a sample key to check the performance.
> [Web][UMA-1125] Encrypt localstorage with a session key

- apps/web/src/components/AccountCard/AccountBalance.test.tsx
- apps/web/src/components/AccountCard/AccountBalance.tsx
- apps/web/src/components/AccountCard/AccountBalanceDetails.test.tsx
- apps/web/src/components/AccountCard/AccountBalanceDetails.tsx
- apps/web/src/components/AccountCard/AccountCard.test.tsx
- apps/web/src/styles/colors.ts
- packages/tezos/src/format.test.ts
- packages/tezos/src/format.ts
[UMA-1157](https://linear.app/tezos/issue/UMA-1157/user-adapt-to-design-present-full-global-stakedunstakedavailable) user: adapt to design - present full global (staked/unstaked/available) balances in UI
Design is here: [UMA-1036](https://linear.app/tezos/issue/UMA-1036/stakingdelegation-design-variants-for-account-component)
| View | Before |Mobile | Web |
| ------ | --- | --- | --- |
| Empty | <img width="300" alt="image" src="https://github.com/user-attachments/assets/02a5e62e-d3c4-4c4e-a745-29c037eb8f49" /> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/ce78b9d2-e9d5-41d1-901b-2d178c11fcb1" /> | <img width="300" alt="image" …
> [Web][UMA-1157] design for delegation and balance

- apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx
- apps/web/src/components/AccountSelectorModal/RemoveAccountModal.tsx
- apps/web/src/components/ConfirmationModal/ConfirmationModal.tsx
[Task link](https://linear.app/tezos/issue/UMA-1071/account-selector-remove-accounts-when-i-remove-an-account-the-account)
> [Web][UMA-1071] Add parameter to keep/close modal on confirmation

- apps/web/package.json
- apps/web/src/components/AccountSelectorModal/AccountSelectorModal.test.tsx
- apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx
- apps/web/src/components/ConfirmationModal/ConfirmationModal.tsx
- pnpm-lock.yaml
[Task link](https://linear.app/tezos/issue/UMA-1074/removing-account-group-or-removing-the-last-account-warn-users-about)
> [Web][UMA-1074] Add warning text for account removal confirmation

- packages/state/src/hooks/backup.test.ts
- packages/state/src/hooks/backup.ts
[Task link](https://linear.app/tezos/issue/UMA-1166/update-backup-logic-for-having-unverified-accounts)
> [UMA-1166] Filter unverified mnemonic accounts from backup file

- apps/web/src/components/AddressAutocomplete/AddressAutocomplete.tsx
- apps/web/src/components/AddressAutocomplete/Suggestions.tsx
- apps/web/src/components/AddressTile/AddressTile.tsx
- apps/web/src/components/AdvancedSettingsAccordion/AdvancedSettingsAccordion.tsx
- apps/web/src/setupTests.ts
[Task link](https://linear.app/tezos/issue/UMA-1167/fix-spaces-for-address-field-on-having-long-balance)
> [Web][UMA-1167] Fix send XTZ ui issues

- apps/desktop/src/components/ChangePassword/ChangePasswordForm.test.tsx
- apps/desktop/src/components/PasswordInput.tsx
- apps/web/src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.test.tsx
- apps/web/src/components/PasswordInput/PasswordInput.tsx
- apps/web/vite.config.ts
- packages/components/src/assets/icons/CheckmarkIcon.tsx
- packages/components/src/assets/icons/index.tsx
- packages/components/src/hooks/usePasswordValidation.test.tsx
- packages/components/src/hooks/usePasswordValidation.tsx
[UMA-693](https://linear.app/tezos/issue/UMA-693/add-password-requirements) Add password requirements
Menu -> add account -> next -> play with password
| Password | Before | Now |
| ---- | ------ | --- |
| empty | <img width="450" alt="image" src="https://github.com/user-attachments/assets/49502155-6b94-43b5-b5c5-dd970b39949b" /> | <img width="450" alt="image" src="https://github.com/user-attachments/assets/816bd7b3-2065-4de7-b6f2-90eaa4922978" /> |
| 123 | <img width="450" alt="image" src="https://github.com/user-attachments/assets/cd8395b3-b969-43b1-8a4d-7484e5a084fa" /> | <img width="450" alt="image" src="https://github.com/user-attachments/assets/bfc65094-f1e5-463a-9014-c3ac6e1064a9" /> |
| 1234567890a! | <img …
> [Web][UMA-693] Password requirements listed

- apps/web/package.json
- apps/web/src/components/App/App.tsx
- apps/web/src/components/Onboarding/OnboardOptions/useOnboardWithSocial.tsx
- apps/web/src/components/Onboarding/SetupPassword/SetupPassword.tsx
- apps/web/src/providers/ReduxStore.tsx
- apps/web/src/utils/persistor.ts
- apps/web/src/utils/store.ts
- apps/web/src/views/SessionLogin/SessionLogin.tsx
- apps/web/src/views/SessionLogin/SignInWithButton.tsx
- apps/web/src/views/SessionLogin/index.ts
- packages/state/src/hooks/session.ts
- packages/state/src/hooks/useAsyncActionHandler.ts
- packages/state/src/reducer.ts
- packages/state/src/slices/accounts/accounts.ts
- packages/state/src/slices/session.ts
- packages/state/src/store.ts
- pnpm-lock.yaml
> [Web][UMA-1129] Add login page UI after session timeout

- apps/web/package.json
- apps/web/src/components/AccountSelectorModal/AccountInfoModal.tsx
- apps/web/src/components/Menu/AddressBookMenu/AddressBookMenu.tsx
- apps/web/src/components/Menu/AdvancedMenu/AdvancedMenu.tsx
- apps/web/src/components/Menu/AppsMenu/AppsMenu.tsx
- apps/web/src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.tsx
- apps/web/src/components/Menu/ErrorLogsMenu/ErrorLogsMenu.tsx
- apps/web/src/components/Menu/Menu.tsx
- apps/web/src/components/Menu/NetworkMenu/EditNetworkMenu.tsx
- apps/web/src/components/Menu/NetworkMenu/NetworkMenu.tsx
- apps/web/src/components/Onboarding/ImportWallet/ImportWallet.tsx
- apps/web/src/components/Onboarding/OnboardOptions/OnboardOptions.tsx
- apps/web/src/components/Onboarding/OnboardOptions/OnboardOptionsModal.tsx
- apps/web/src/components/SendFlow/Delegation/FormPage.tsx
- apps/web/src/components/SendFlow/NFT/FormPage.tsx
- apps/web/src/components/SendFlow/Stake/FormPage.tsx
- apps/web/src/components/SendFlow/Tez/FormPage.tsx
- apps/web/src/components/SendFlow/Token/FormPage.tsx
- apps/web/src/components/SendFlow/Undelegation/FormPage.tsx
- apps/web/src/components/SendFlow/Unstake/FormPage.tsx
- apps/web/src/components/SendFlow/common/BatchSignPage.tsx
- apps/web/src/components/SendFlow/common/SingleSignPage.tsx
- apps/web/src/env.ts
- apps/web/src/main.tsx
- apps/web/src/utils/hotjar.ts
- pnpm-lock.yaml
[UMA-1092](https://linear.app/tezos/issue/UMA-1092/set-up-hotjar-remember-to-hide-confidential-information) Set up Hotjar: remember to hide confidential information
> [Web][UMA-1092] setting up Hotjar for staging

- apps/web/package.json
- apps/web/src/env.ts
- apps/web/src/main.tsx
- apps/web/src/utils/sentry.ts
- pnpm-lock.yaml
[Task link](https://linear.app/tezos/issue/UMA-1180/add-sentry-to-umami-web)
Add sentry to the web app
> [Web][UMA-1180] Integrate Sentry to web

- apps/web/src/components/Menu/AppsMenu/AppsMenu.tsx
[UMA-1193](https://linear.app/tezos/issue/UMA-1193/infomark-html-error-div-in-p) InfoMark html error <div> in <p>
Menu --> Apps
|        | <img width="400" alt="image" src="https://github.com/user-attachments/assets/6af0c5f3-28d8-4e7a-8ed2-2ed6f0470fea" /> |
> [Web][UMA-1193] Html error for InforMark

- packages/core/src/helpers.ts
- packages/state/src/hooks/session.ts
Fix the issue when social auth timeout expires too fast
> [Web] Fix social backup timeout issue

- packages/state/src/walletConnect/WalletKit.ts
[UMA-1189](https://linear.app/tezos/issue/UMA-1189/walletconnect-update-walletconnect-id-for-umami) WalletConnect: update WalletConnect ID for Umami
> [Web][UMA-1189] Updating WalletConnect project ID

- apps/web/src/components/Onboarding/ImportWallet/ImportBackupTab.tsx
- apps/web/src/views/SessionLogin/SessionLogin.tsx
- packages/state/src/hooks/backup.test.ts
- packages/state/src/hooks/backup.ts
- packages/state/src/hooks/session.ts
[Task link](https://linear.app/tezos/issue/UMA-1216/incorrect-password-error-takes-back-to-the-welcome-screen-when)
> [Web][UMA-1216] Fix incorrect password error within backup flow

- apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.tsx
- apps/web/src/components/AccountSelectorModal/RenameAccountModal.tsx
- apps/web/src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.tsx
- apps/web/src/components/Onboarding/OnboardOptions/useOnboardWithSocial.tsx
- apps/web/src/components/SendFlow/SignButton.tsx
- apps/web/src/components/SendFlow/onSubmitFormActionHooks.tsx
- apps/web/src/components/WalletConnect/WalletConnectProvider.tsx
- apps/web/src/components/WalletConnect/useHandleWcRequest.tsx
- apps/web/src/components/beacon/BeaconProvider.tsx
- apps/web/src/components/common/SignPayloadRequestModal.tsx
- apps/web/src/providers/UmamiTheme.tsx
- packages/utils/src/providers/ToastProvider.tsx
[Task link](https://linear.app/tezos/issue/UMA-1237/fix-custom-toast)
|![image](https://github.com/user-attachments/assets/71a0893d-04ea-4853-95f9-3d379ef05314)|<img width="322" alt="image" src="https://github.com/user-attachments/assets/705e1a4a-dc41-4492-a7df-f4b263c64d90" />|
> [Web][UMA-1237] Replace Chakra useToast with custom useCustomToast

- apps/web/src/components/Onboarding/OnboardOptions/useOnboardWithSocial.tsx
[Task link](https://linear.app/tezos/issue/UMA-1069/account-selector-add-account-after-adding-an-account-the-connect-modal)
> [Web][UMA-1069 ] Close the modal window after successfully adding an account

- apps/web/src/components/AddressTile/AddressTile.tsx
- apps/web/src/components/SendFlow/Tez/FormPage.test.tsx
- apps/web/src/components/SendFlow/Tez/FormPage.tsx
[UMA-1207](https://linear.app/tezos/issue/UMA-1207/white-icon-on-send-tez-initiated-locally) White icon on Send Tez initiated locally
| Size | Before | Now |
| -- | ------ | --- |
| Mobile | <img width="300" alt="image" src="https://github.com/user-attachments/assets/a5f1dfa4-f14b-4a6d-8107-d9cc6ddd4a39" /> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/aaaa6751-2dba-409b-ae29-6f926cd009d8" /> |
| Laptop | <img width="300" alt="image" src="https://github.com/user-attachments/assets/c5c6b691-d0c7-4ddd-9b63-7fe679bbc220" /> |  <img width="300" alt="image" src="https://github.com/user-attachments/assets/92e17d66-ea71-4d3d-b212-1d4c5ce7a8b3" /> |
Request from dApp
| -- | …
> [Web][UMA-1207] Account logo on local send

- apps/web/src/components/AccountTile/AccountTile.tsx
- apps/web/src/components/Header/Header.tsx
[Task link](https://linear.app/tezos/issue/UMA-1064/account-card-selector-when-scrolling-down-on-mobile-tapping-on-the)
|<img width="326" alt="image" src="https://github.com/user-attachments/assets/9ad99186-4a00-4158-a799-84989c9e2b19" />|<img width="425" alt="image" src="https://github.com/user-attachments/assets/7d3c2e7d-a469-4131-83dc-f864960fe16d" />|
> [Web][UMA-1064] Update mobile header

- apps/web/src/views/NFTs/NFTDrawer.tsx
- apps/web/src/views/NFTs/NFTDrawerCard/AttributesAccordion.tsx
[Task link](https://linear.app/tezos/issue/UMA-1236/fix-nft-drawer-ui)
This PR introduces couple minor nft drawer ui fixes
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/d0416753-e273-41b2-b8c0-fe388eb62da9" />|<img width="300" alt="image" src="https://github.com/user-attachments/assets/2381c6b3-20de-491b-b341-048537c17a67" />|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/bc3bb6ae-a717-4401-8805-b12c6b7bcccb" />|<img width="300" alt="image" src="https://github.com/user-attachments/assets/d994c98f-ff7f-419b-bef4-a38fa532aa27" />|
> [Web][UMA-1236] Improve NFT drawer styling

- packages/chains/.depcheckrc
- packages/chains/.eslintrc.cjs
- packages/chains/babel.config.json
- packages/chains/jest.config.ts
- packages/chains/package.json
- packages/chains/src/index.ts
- packages/chains/src/indexers/index.ts
- packages/chains/src/indexers/tezos/index.ts
- packages/chains/src/indexers/tezos/tzkt/fetch.test.ts
- packages/chains/src/indexers/tezos/tzkt/fetch.ts
- packages/chains/src/indexers/tezos/tzkt/index.ts
- packages/chains/src/indexers/tezos/tzkt/schemas.ts
- packages/chains/src/indexers/tezos/tzkt/testUtils.ts
- packages/chains/src/indexers/tezos/tzkt/types.ts
- packages/chains/src/indexers/tezos/tzkt/withRateLimit.test.ts
- packages/chains/src/indexers/tezos/tzkt/withRateLimit.ts
- packages/chains/src/setupTests.ts
- packages/chains/tsconfig.json
- pnpm-lock.yaml
[Task link](https://linear.app/tezos/issue/UMA-1264/multi-chain-move-packagestzkt-to-packageschains)
no changes to the logic 
github tests
> [Web][UMA-1264] Multi-chain: Move @umami/tzkt to @umami/chains

- apps/web/src/components/Main/Main.tsx
- apps/web/src/components/OperationTile/OperationTileView.tsx
[Task link](https://linear.app/tezos/issue/UMA-1062/activity-tab-tez-transfer-amount-is-aligned-differently-from-token)
|![image](https://github.com/user-attachments/assets/325ac1a3-3aba-40f5-b8fd-89fb39053014)|<img width="826" alt="image" src="https://github.com/user-attachments/assets/5a51aa07-fc4b-4bc5-ba2f-ab1170afae72" />|
Please add descriptions of tests added here. How they verify the feature.
> [Web][UMA-1062] Fix activity tab ui issues

- apps/web/src/components/Tag/Tag.tsx
- apps/web/src/styles/theme.ts
- apps/web/src/views/NFTs/NFTFilter/NFTFilter.test.tsx
- apps/web/src/views/NFTs/NFTFilter/NFTFilter.tsx
- apps/web/src/views/NFTs/NFTFilter/useNFTFilter.test.ts
- apps/web/src/views/NFTs/NFTFilter/useNFTFilter.ts
- apps/web/src/views/NFTs/NFTs.tsx
[Task link](https://linear.app/tezos/issue/UMA-1055/nfts-filter-by-filter-by-and-my-total-nfts-number-on-the-right-hand)
|<img width="829" alt="image" src="https://github.com/user-attachments/assets/03a90020-9858-4c46-8a63-ec811d1750e2" />|<img width="846" alt="image" src="https://github.com/user-attachments/assets/308eb7ee-2389-4a7a-b5fd-ec5310491226" />|
Please add descriptions of tests added here. How they verify the feature.
> [Web][UMA-1055] Fix NFT filter by ui

- packages/state/src/store.ts
[Task link](https://linear.app/tezos/issue/UMA-1282/persistent-state-undefined-causes-runtime-error)
Please add descriptions of tests added here. How they verify the feature.
> [Web][UMA-1282] Fix runtime error when state.account is undefined

- apps/oauth/public/redirect.html
[Task link](alessandrocatania/uma-1527)
Please add descriptions of tests added here. How they verify the feature.
> [Web][UMA-1527] Update the social login redirection to dev.umamiwallet.com
