src/components/AccountDrawer/AssetsPanel/OperationListDisplay.test.tsx, src/components/AccountDrawer/AssetsPanel/OperationListDisplay.tsx, src/components/NoItems/index.tsx
[Task link]()
Open account drawer for account without operations.
|    <img width="563" alt="Screenshot 2024-02-23 at 04 57 23" src="https://github.com/trilitech/umami-v2/assets/150050388/2b5d9579-8b21-457c-98be-9c28e9fc3b98">    |   <img width="588" alt="Screenshot 2024-02-23 at 04 56 38" src="https://github.com/trilitech/umami-v2/assets/150050388/3c552a19-7b6b-4ac2-8d48-f5211e40c846">  |
=> Remove "View all" button from Operations empty state

src/components/SendFlow/SignButton.tsx
The toast stayed open even after error / successful sign with ledger.
[Task link](https://app.asana.com/0/1205770721172203/1206597776005797/f)
Initiate transaction from ledger account & try signing it (successfully or not)
https://github.com/trilitech/umami-v2/assets/150050388/448c3fa1-1c5f-4bee-9726-f1609b6bde48
https://github.com/trilitech/umami-v2/assets/150050388/f8528d12-ebb6-4c5b-8169-5155fdc1ac51
=> Close ledger toast on sign action completion

package.json, scripts/build.js
- we don't support snap at the moment
- the app requires libasound2, other dependencies are takes from [the documentation](https://www.electron.build/configuration/linux#debian-package-options)
- homepage is used both by the app description and webpack when it builds the app, so I split them up
=> Update package details for linux distributions

src/components/SendFlow/Delegation/FormPage.test.tsx, src/components/SendFlow/MultisigAccount/NameMultisigFormPage.test.tsx, src/components/SendFlow/MultisigAccount/SelectApproversFormPage.test.tsx, src/components/SendFlow/NFT/FormPage.test.tsx, src/components/SendFlow/Tez/FormPage.test.tsx, src/components/SendFlow/Token/FormPage.test.tsx, src/components/SendFlow/Undelegation/FormPage.test.tsx, src/mocks/dynamicModal.tsx, src/mocks/testUtils.tsx
this way we don't need to manually wrap our components with the context. the spying functions are always there and we don't lose the original implementation, it still renders the modal on the page
=> Simplify dynamicModalContextMock usage

src/utils/beacon/BeaconPeers.tsx
DApp might have the same name, but different beacon instances.
E. g. on mainnet & ghostnet, or when trying to connect from different browsers.
SenderId is unique for each beacon instance of a dApp, so using it as a key solves this problem.
Connect to the same dApp from different browsers. Check console for errors.
|    <img width="1225" alt="Screenshot 2024-03-12 at 14 00 38" src="https://github.com/trilitech/umami-v2/assets/150050388/9889ff27-b8b8-4eeb-8418-f2611a10f103">    |   <img width="875" alt="Screenshot 2024-03-12 at 14 02 27" src="https://github.com/trilitech/umami-v2/assets/150050388/affb457b-4e93-4ae3-946e-5f57a42c6f9d">  |
=> Fix duplicating key error for peers

src/components/SendFlow/MultisigAccount/SignTransactionFormPage.tsx, src/components/SendFlow/utils.tsx, src/utils/hooks/useAsyncActionHandler.test.ts, src/utils/hooks/useAsyncActionHandler.ts
- This improves performance because the functions do not get recreated all the time
- It allows to use those functions in useEffect's or similar hooks' dependency arrays
- It doesn't depend on the render cycle anymore and should be much safer in terms of race conditions
- fixed a bug in multisig creation part where the same handleAsyncAction was reused which might not let the contract name get assigned
=> Memoize handleAsyncAction functions

src/components/useAccountsFilter.test.tsx, src/components/useAccountsFilter.tsx
Now the selected accounts object is cached and won't change until we actually update the list of selected accounts. Since useGetOperations relies on it, it's helpful to use the object as a dependency in useEffect or similar hooks and ovoid unnecessary requests
=> Optimize useAccountsFilter hook

src/components/Offboarding/OffboardingForm.tsx, src/utils/hooks/setAccountDataHooks.ts
Sometimes beacon would throw an error if we only cleaned the local storage.
also, it might be that redux persist flushes the state to the local storage right after we've just cleaned it.
also, `useReset` has never been a hook
=> Safer offboarding

package.json, yarn.lock
It's deprecated and has already been replaced with @testing-library/react
=> Remove react-test-renderer dependency

src/components/Onboarding/restoreSecretKey/RestoreSecretKey.test.tsx, src/components/Onboarding/restoreSecretKey/RestoreSecretKey.tsx, src/components/PasswordInput.tsx
[Task link](https://app.asana.com/0/1205770721172203/1207311817583468/f)
|<img width="532" alt="image" src="https://github.com/trilitech/umami-v2/assets/169451151/ce458d68-307f-49b0-a6cb-22c338736876">|<img width="513" alt="image" src="https://github.com/trilitech/umami-v2/assets/169451151/69cda1ed-faae-4726-a8ac-50d9f9fa402d">|
=> Fix secret key import error

src/components/SendFlow/Beacon/BatchSignPage.tsx, src/components/SendFlow/Beacon/ContractCallSignPage.tsx, src/components/SendFlow/Beacon/DelegationSignPage.tsx, src/components/SendFlow/Beacon/TezSignPage.test.tsx, src/components/SendFlow/Beacon/TezSignPage.tsx, src/components/SendFlow/Beacon/UndelegationSignPage.tsx, src/components/SendFlow/Beacon/useSignWithBeacon.tsx, src/components/SendFlow/SignButton.tsx, src/utils/beacon/BeaconPeers.test.tsx, src/utils/beacon/BeaconPeers.tsx, src/utils/beacon/PermissionRequestModal.test.tsx, src/utils/beacon/PermissionRequestModal.tsx, src/utils/beacon/SignPayloadRequestModal.test.tsx, src/utils/beacon/SignPayloadRequestModal.tsx, src/utils/beacon/beacon.tsx, src/utils/beacon/useHandleBeaconMessage.test.tsx, src/utils/beacon/useHandleBeaconMessage.tsx, src/utils/hooks/beaconHooks.ts, src/utils/hooks/networkHooks.test.ts, src/utils/hooks/networkHooks.ts, src/utils/hooks/removeAccountDependenciesHooks.test.ts
- when we get a request from beacon on an unknown network we throw an exception
- when we get an operatino request from beacon on a non-current network, we run the estimation and the execution on the correct one
- if we close permission or payload sign modals we send a close connection message back to the dApp and remove it from the beacon connections list 
play around with [the dApp](https://042fd6ee.taquito-test-dapp.pages.dev/)
=> Improve communication through beacon

src/components/SendFlow/Beacon/BeaconSignPage.tsx, src/components/SendFlow/Beacon/OriginationOperationSignPage.test.tsx, src/components/SendFlow/Beacon/OriginationOperationSignPage.tsx, src/utils/beacon/useHandleBeaconMessage.test.tsx, src/utils/beacon/useHandleBeaconMessage.tsx
[Task link](https://app.asana.com/0/1205770721172203/1207253876711110/f)
=> Add origination operation page

src/utils/tezos/helpers.test.ts, src/utils/tezos/helpers.ts
here's [the reason why](https://taquito.io/docs/originate#b-initializing-storage-using-a-plain-michelson-expression-for-initial-storage)
try to deploy a token [here](https://tezos-homebase.io/creator/deployment/summary)
=> Fix contract origination with Michelson storage

src/components/SendFlow/Batch/SignPage.test.tsx, src/components/SendFlow/Beacon/BatchSignPage.tsx, src/components/SendFlow/Beacon/OriginationOperationSignPage.test.tsx, src/components/SendFlow/Delegation/SignPage.test.tsx, src/components/SendFlow/Multisig/SignPage.test.tsx, src/components/SendFlow/Multisig/SignPage.tsx, src/components/SendFlow/MultisigAccount/SignTransactionFormPage.test.tsx, src/components/SendFlow/NFT/SignPage.test.tsx, src/components/SendFlow/SignButton.tsx, src/components/SendFlow/Tez/SignPage.test.tsx, src/components/SendFlow/Token/SignPage.test.tsx, src/components/SendFlow/Undelegation/SignPage.test.tsx, src/utils/beacon/SignPayloadRequestModal.test.tsx, src/utils/beacon/SignPayloadRequestModal.tsx
[Task link](https://app.asana.com/0/1205770721172203/1207485746787126/f)
=> Add form isValid check for SignButton

src/components/AdvancedSettingsAccordion.tsx, src/components/SendFlow/BatchModalBody.tsx, src/components/SendFlow/Multisig/SignPage.tsx
[Task link](https://app.asana.com/0/1205770721172203/1207485730920775/f)
=> Add advanced settings to multisig sign page

src/components/SendFlow/MultisigAccount/SignTransactionFormPage.tsx, src/mocks/helpers.ts, src/types/AccountOperations.ts, src/utils/hooks/setAccountDataHooks.test.ts, src/utils/mnemonic.test.ts, src/utils/mnemonic.ts, src/utils/tezos/estimate.test.ts, src/utils/tezos/estimate.ts, src/utils/tezos/helpers.test.ts, src/utils/tezos/helpers.ts, src/utils/tzkt/types.ts
New accounts, even if they are funded, until there is a reveal operation, remain unrevealed, meaning that the signer has to execute a reveal operation before making any others.
Taquito deals with that by prepending the reveal operation to the operations list on the estimation and it returns the estimation of it as the first in the estimates list.
=> Fix operations execution for unrevealed accounts

apps/desktop/src/utils/dataPolling/useDataPolling.test.ts, apps/desktop/src/utils/dataPolling/useDataPolling.ts
[Task link](https://app.asana.com/0/1205770721172203/1207485730920781/f)
=> Update useDataPolling hook to show only one notification

apps/desktop/electron-builder.yml
electron builder doesn't play well with monorepo setup (on linux only) so we have to rename the artifacts ourselves, otherwise, it fails with "I cannot create a dist/@umami/desktop folder blablabla"
=> Fix linux builds

apps/desktop/src/components/DynamicModal.tsx, apps/desktop/src/components/SendFlow/Beacon/BatchSignPage.tsx, apps/desktop/src/components/SendFlow/Beacon/FinalizeUnstakeSignPage.tsx, apps/desktop/src/components/SendFlow/Beacon/StakeSignPage.tsx, apps/desktop/src/components/SendFlow/Beacon/UnstakeSignPage.tsx, apps/desktop/src/mocks/modal.tsx, apps/desktop/src/setupTests.ts, apps/desktop/src/utils/beacon/PermissionRequestModal.tsx, apps/desktop/src/utils/beacon/SignPayloadRequestModal.tsx, apps/desktop/src/utils/beacon/useHandleBeaconMessage.test.tsx, apps/desktop/src/utils/beacon/useHandleBeaconMessage.tsx, apps/desktop/src/views/batch/BatchView.tsx
1. Beacon staking operations components weren't wrapped into a FormProvider, and signing didn't work.
2. When beacon operation modal was closed, it wouldn't send an error to the dapp
| https://github.com/trilitech/umami-v2/assets/129749432/ad6ca28d-51ce-4a35-9391-ddee1923e130 | https://github.com/trilitech/umami-v2/assets/129749432/5cff1f49-0143-4848-aaef-91f93d175085 |
| https://github.com/trilitech/umami-v2/assets/129749432/934fc9cb-ca88-423d-b2e6-9f44e8993ee8 | https://github.com/trilitech/umami-v2/assets/129749432/6a85c3cb-f743-42cd-8074-b5a6204e8a3c |
=> Fix beacon signing

.github/workflows/test.yaml, package.json
these jobs underneath use concurrency/parallelism themselves. so, even if we have just 2 jobs, 4 CPU cores, they both would compete for all 4 cores, and it leads, sometimes, to timeouts
=> Run test jobs in CI sequentially

package.json, packages/components/package.json, packages/core/package.json, packages/crypto/package.json, packages/data-polling/package.json, packages/jest-config/package.json, packages/multisig/package.json, packages/social-auth/package.json, packages/state/package.json, packages/test-utils/package.json, packages/tezos/package.json, packages/tzkt/package.json, turbo.json
this speeds up dev experience. DTS processing takes 10-20x more time than building actual js files.
type-checking might suffer a bit from this change, but VScode consumes the types from the typescript files anyway, not the dts.
the problematic parts are circular deps check and (potentially) linting which relies on types. but it'll be checked properly on CI anyway
=> Add build:quick turbo task

apps/desktop-e2e/src/helpers/AccountGroup.ts, apps/desktop/package.json, apps/desktop/src/components/Onboarding/masterPassword/MasterPassword.tsx, apps/desktop/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.test.tsx, apps/desktop/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.tsx, apps/web/package.json, apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTabPanel.test.tsx, apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTabPanel.tsx, apps/web/src/components/Onboarding/SetupPassword/SetupPassword.test.tsx, apps/web/src/components/Onboarding/SetupPassword/SetupPassword.tsx, apps/web/src/components/Onboarding/SetupPassword/index.ts, apps/web/src/components/Onboarding/masterPassword/MasterPassword.tsx, apps/web/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.test.tsx, apps/web/src/components/Onboarding/restoreMnemonic/RestoreMnemonic.tsx, apps/web/src/components/RadioButtons/RadioButtons.test.tsx, apps/web/src/components/RadioButtons/RadioButtons.tsx, apps/web/src/components/RadioButtons/index.ts, apps/web/src/testUtils.tsx, packages/components/src/DynamicDisclosure/useMultiForm.tsx, packages/state/jest.config.ts, packages/state/src/hooks/backup.ts, packages/state/src/hooks/mnemonic.test.ts, packages/state/src/hooks/mnemonic.ts, packages/state/src/hooks/setAccountData.test.ts, packages/state/src/hooks/setAccountData.ts, packages/tezos/src/helpers.ts
[Task link](https://app.asana.com/0/1207041888417083/1207985676541269/f)
This PR also adds logic for deriving mnemonic accounts with curves different to ed25519
https://github.com/user-attachments/assets/c3f3d4d0-8010-407f-9d8b-f8e46f27037a
=> Add password step for seedphrase import

apps/web/src/components/AccountCard/AccountCard.tsx, apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx, apps/web/src/components/AccountSelectorModal/AccountSelectorPopover.tsx, apps/web/src/components/AccountTile/AccountTile.tsx, apps/web/src/components/Header/Header.tsx, apps/web/src/components/Menu/AddressBookMenu/AddressBookMenu.tsx, apps/web/src/components/beacon/BeaconPeers.tsx, apps/web/src/setupTests.ts
[Task link](https://app.asana.com/0/1207041888417083/1208109932329503/f)
https://github.com/user-attachments/assets/bf9520b4-7168-46ea-ab4e-352fe17ea1e4
=> Add account tile to mobile header

apps/embed-iframe/src/OperationModalContent.tsx, apps/embed-iframe/src/operationModalHooks.tsx, apps/embed-iframe/src/utils.ts
- This change makes it possible to only show iframe when fee computation is completed 
- If there is an error during computation, dApp will get it, but the user won't see the iframe
[Task link](https://app.asana.com/0/1207646563234653/1208056016062017/f)
https://github.com/user-attachments/assets/5685ac6e-3c0d-49d7-b369-e95149bb2ad5
https://github.com/user-attachments/assets/a7ecdccf-55e9-4343-904a-b2c09f3c7276
=> Send message to Embed Component when fee estimation completed

apps/web/src/components/AccountSelectorModal/AccountSelectorModal.test.tsx, apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx, apps/web/src/components/AccountSelectorModal/RemoveAccountModal.tsx, apps/web/src/components/ConfirmationModal/ConfirmationModal.tsx, apps/web/src/components/ConfirmationModal/index.ts, apps/web/src/components/Menu/LogoutModal.tsx
[Task link](https://app.asana.com/0/1207041888417083/1208109932369879/f)
https://github.com/user-attachments/assets/4a9cb780-2b2f-48d1-8d3e-ee3e88f5a5b0
=> Add remove account group

apps/desktop/electron-builder.dev.yml, apps/desktop/electron-builder.yml, apps/desktop/package.json, apps/desktop/public/electron.js, apps/desktop/scripts/afterPack.js, apps/desktop/tsconfig.json, pnpm-lock.yaml
universal mac package is impossible to build with the integrity check because arm build contains more files than the amd64
files are now served using a custom protocol because file:// is too permissive
build the app and sign it
=> Improve electron fuses setup

apps/desktop/src/utils/beacon/SignPayloadRequestModal.test.tsx, apps/desktop/src/utils/beacon/SignPayloadRequestModal.tsx, apps/desktop/src/utils/beacon/useHandleBeaconMessage.test.tsx, apps/web/src/components/beacon/SignPayloadRequestModal.test.tsx, apps/web/src/components/beacon/SignPayloadRequestModal.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, packages/core/package.json, packages/core/src/decodeBeaconPayload.test.ts, packages/core/src/decodeBeaconPayload.ts, pnpm-lock.yaml
now we:
- can parse encoded operations
- show raw payload if user switches the toggle
- fail parsing if it's not a valid UTF-8
=> Improve Beacon payload parsing

apps/oauth/public/redirect.html
[Security review issue](https://github.com/trilitech/umami-security-review/issues/9)
This PR adds ghostnet deployment url to oauth redirect.
This is preparation for splitting ghostnet & mainnet environments on Vercel:
- Mainnet will have frame-ancestors for allowlisted dApps only. 
- Ghostnet will work for any url, but for ghostnet requests only.
Once everything is set up and tested, I'll add frame-ancestors to `vercel.mainnet.json`
=> Add embed ghostnet url to oauth redirect page

apps/embed-iframe/src/EmbeddedComponent.tsx, apps/embed-iframe/src/env.ts
[Security review issue](https://github.com/trilitech/umami-security-review/issues/9)
This PR ands environment variables and blocks mainnet requests from execution on ghostnet deployment.
This is preparation for splitting ghostnet & mainnet environments on Vercel:
- Mainnet will have frame-ancestors for allowlisted dApps only. 
- Ghostnet will work for any url, but for ghostnet requests only.
Once everything is set up and tested, I'll add frame-ancestors to `vercel.mainnet.json`
=> [embed] Block mainnet requests on ghostnet deployment

apps/web/index.html, apps/web/src/components/Footer/Footer.tsx, apps/web/src/components/Onboarding/ImportWallet/ImportBackupTab.tsx, apps/web/src/components/Onboarding/OnboardOptions/OnboardOptions.tsx, apps/web/src/components/Onboarding/OnboardOptions/useOnboardWithSocial.tsx, apps/web/src/utils/analytics.ts
[Task link](https://app.asana.com/0/1207041888417083/1208008227231534/f)
[Event Requirements](https://www.notion.so/tezosfoundation/Analytics-for-Umami-374af98bcb284b53af4d1f89c3132d35)
Onboarding
=> Add Google Analytics to web

apps/desktop/src/components/AccountDrawer/AccountDrawerDisplay.test.tsx, apps/desktop/src/setupTests.tsx, apps/desktop/src/views/operations/OperationsView.tsx, apps/web/src/setupTests.ts, apps/web/src/views/Activity/Activity.tsx, packages/data-polling/src/useGetOperations.tsx
This PR fixes infinite scroll on web
=> Fix infinite scroll on Operations and Activity pages

apps/desktop/package.json, apps/desktop/vite.config.ts, apps/embed-iframe-mainnet/package.json, apps/embed-iframe-mainnet/src/vite-env.d.ts, apps/embed-iframe-mainnet/vite.config.ts, apps/embed-iframe/package.json, apps/embed-iframe/src/vite-env.d.ts, apps/embed-iframe/vite.config.ts, apps/web/package.json, apps/web/vite.config.ts, global.d.ts, packages/typescript-config/tsconfig.json, pnpm-lock.yaml
[Security review issue link](https://github.com/trilitech/umami-security-review/issues/39)
Use SRI in the production environment when loading third-party or CDN-hosted assets, to ensure the browser rejects any assets whose content does not match the expected hash.
=> Add subresource integrity

apps/web/src/components/AddContactModal/AddContactModal.test.tsx, apps/web/src/components/AddContactModal/AddContactModal.tsx, apps/web/src/components/AddContactModal/index.ts, apps/web/src/components/AddressPill/RightIcon.tsx
[Task link](https://app.asana.com/0/1207041888417083/1208648725384603/f)
|<img width="1498" alt="image" src="https://github.com/user-attachments/assets/641fd334-5fe1-4cb5-b783-cc6fe0f0fba0">|<img width="1512" alt="image" src="https://github.com/user-attachments/assets/db06bd93-1b52-411b-9f27-845d99609abb">|
=> Implement AddContactModal

package.json, pnpm-lock.yaml
see https://github.com/trilitech/umami-v2/security/dependabot
for some reason, dependabot couldn't resolve those packages on its own
=> Bump vulnerable packages

apps/desktop/src/components/AddressPill/AddressPill.tsx, packages/core/src/Operation.ts, packages/tezos/src/Address.test.ts, packages/tezos/src/Address.ts, packages/tezos/src/testUtils.ts, packages/tezos/src/types.ts
This PR fixes Smart Rollup addresses parsing
=> Add smart rollup address support

apps/desktop/electron-builder.yml, apps/desktop/package.json
electron-builder deprecated the original method
=> Set APPLE_TEAM_ID through an env var

.github/workflows/release.yaml
Build the apps for all platforms (windows, linux and mac) on github CI.
[Task link]()
=> Add a build workflow on all platforms

apps/desktop/electron-builder.yml, apps/desktop/entitlements.mac.plist
This PR `disables` these entitlements for MacOS desktop app
```
com.apple.security.cs.allow-unsigned-executable-memory
com.apple.security.cs.disable-library-validation
```
=> Adjust mac entitlements for desktop

apps/embed-iframe-mainnet/vercel.json, apps/embed-iframe/vercel.json, apps/web/src/components/AccountCard/AccountBalance.test.tsx, apps/web/src/components/AccountSelectorModal/DeriveMnemonicAccountModal/DeriveMnemonicAccountModal.test.tsx, apps/web/src/components/CopyButton/CopyButton.test.tsx, apps/web/src/components/MasterPasswordModal/MasterPasswordModal.test.tsx, apps/web/src/components/Menu/AdvancedMenu/AdvancedMenu.test.tsx, apps/web/src/components/Onboarding/ImportWallet/ImportBackupTab.test.tsx, apps/web/src/components/SendFlow/utils.test.tsx, apps/web/src/components/beacon/PermissionRequestModal.test.tsx, apps/web/src/setupTests.ts, packages/state/src/migrations.test.ts, packages/state/src/migrations.ts, packages/tezos/src/Network.ts
Issues were found related to the RPX nodes we ='re using at the moment. We're switching to new nodes controlled by ECAD labs.
[Security review task link #48](https://github.com/trilitech/umami-security-review/issues/48)
[Security review task link #47](https://github.com/trilitech/umami-security-review/issues/47)
=> Set new Tezos RPC nodes

apps/desktop/src/Router.tsx, apps/desktop/src/utils/beacon/BeaconPeers.tsx, apps/desktop/src/utils/beacon/PermissionRequestModal.tsx, apps/desktop/src/utils/beacon/useHandleBeaconMessage.tsx, apps/web/src/components/Menu/AppsMenu/AppsMenu.test.tsx, apps/web/src/components/Menu/AppsMenu/AppsMenu.tsx, apps/web/src/components/Menu/Menu.test.tsx, apps/web/src/components/WalletConnect/SessionProposalModal.tsx, apps/web/src/components/WalletConnect/WalletConnectPeers.tsx, apps/web/src/components/WalletConnect/WalletConnectProvider.tsx, apps/web/src/components/WalletConnect/index.tsx, apps/web/src/components/beacon/BeaconPeers.tsx, apps/web/src/components/beacon/PermissionRequestModal.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx, packages/state/package.json, packages/state/src/hooks/WalletConnect.ts, packages/state/src/hooks/beacon.test.ts, packages/state/src/hooks/beacon.ts, packages/state/src/hooks/index.ts, packages/state/src/hooks/removeAccountDependencies.ts, packages/state/src/reducer.ts, packages/state/src/slices/WalletConnect.ts, packages/state/src/slices/beacon.ts, packages/state/src/slices/index.ts, pnpm-lock.yaml
Adding peers for WalletConnect
- adding walletconnect to slices
- updating peer list on connect and disconnect
1. Rejecting
actions: on dApp - connect, copy link. on Wallet: Connect, reject
result: on Wallet - Approve button is inactive. On reject - modal is closed immediately. on dApp: modal is closed
2. Approving
actions: on dApp - connect, copy link. on Wallet: on Wallet: Connect, select Account, Approve
result: on dApp - connected, the list of actions is shown. on Wallet: the modal is closed, the list of peers contains the dApp (name, account, network, button to disconnect)
actions: on dApp - request transaction
result: on dApp - transaction is immediately rejected with USER rejected error
3. Disconnecting from Wallet
actions: connect with approve; click Disconnect on Wallet
result: …
=> feat: Adding WalletConnect data to peer list and slices

apps/desktop/src/components/Onboarding/restoreBackupFile/RestoreBackupFile.test.tsx, apps/desktop/src/components/SendFlow/Delegation/FormPage.test.tsx, apps/desktop/src/components/SendFlow/Tez/FormPage.test.tsx, apps/desktop/src/components/SendFlow/Undelegation/FormPage.test.tsx, apps/desktop/src/utils/beacon/useHandleBeaconMessage.test.tsx, apps/desktop/src/views/batch/BatchView.test.tsx, apps/web/src/components/SendFlow/Delegation/FormPage.test.tsx, apps/web/src/components/SendFlow/Tez/FormPage.test.tsx, apps/web/src/components/SendFlow/Undelegation/FormPage.test.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, packages/tezos/src/helpers.ts
Fixing this test which fails on `main`
```
● <Form /> › single transaction › shows a toast if estimation fails
expect(jest.fn()).toHaveBeenCalledWith(...expected)
- Expected
+ Received
Object {
-   "description": "Some error occurred",
+   "description": "Something went wrong. Please try again or contact support if the issue persists.",
"isClosable": true,
"status": "error",
},
Number of calls: 1
101 |
102 |       expect(estimateMock).toHaveBeenCalledTimes(1);
> 103 |       expect(mockToast).toHaveBeenCalledWith({
|                         ^
104 |         description: "Some error occurred",
105 |         status: "error",
106 |         isClosable: true,
```
=> Fix custom error handling

apps/web/src/components/SendFlow/Beacon/BatchSignPage.tsx, apps/web/src/components/SendFlow/Beacon/BeaconSignPage.tsx, apps/web/src/components/SendFlow/Beacon/BeaconSignPageProps.ts, apps/web/src/components/SendFlow/Beacon/ContractCallSignPage.tsx, apps/web/src/components/SendFlow/Beacon/DelegationSignPage.tsx, apps/web/src/components/SendFlow/Beacon/FinalizeUnstakeSignPage.tsx, apps/web/src/components/SendFlow/Beacon/Header.tsx, apps/web/src/components/SendFlow/Beacon/OriginationOperationSignPage.test.tsx, apps/web/src/components/SendFlow/Beacon/OriginationOperationSignPage.tsx, apps/web/src/components/SendFlow/Beacon/StakeSignPage.tsx, apps/web/src/components/SendFlow/Beacon/TezSignPage.test.tsx, apps/web/src/components/SendFlow/Beacon/TezSignPage.tsx, apps/web/src/components/SendFlow/Beacon/UndelegationSignPage.tsx, apps/web/src/components/SendFlow/Beacon/UnstakeSignPage.tsx, apps/web/src/components/SendFlow/Beacon/useSignWithBeacon.tsx, apps/web/src/components/SendFlow/utils.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx
Preparing Umami web for handling WalletConnect requests.
The modals and tests are prepared to be used for both Beacon and WalletConnect.
There are no visible or functional changes.
=> feat: WalletConnect integration, part 3, Beacon modals generalised for any SDK

apps/web/src/components/SendFlow/Beacon/BatchSignPage.tsx, apps/web/src/components/SendFlow/Beacon/BeaconSignPage.tsx, apps/web/src/components/beacon/BeaconPeers.tsx, apps/web/src/components/beacon/PermissionRequestModal.tsx, apps/web/src/components/beacon/SignPayloadRequestModal.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx, packages/eslint-config/index.js
This rule prevents unnecessary path segments in import and require statements.
This rule is automatically fixable by the `--fix CLI option`.
=> Add import/no-useless-path-segments rule to eslint-config

apps/desktop/src/Router.tsx, apps/desktop/src/components/Onboarding/verifySeedphrase/VerifySeedphrase.tsx, apps/desktop/src/components/SocialLoginWarningModal/SocialLoginWarningModal.test.tsx, apps/desktop/src/components/SocialLoginWarningModal/SocialLoginWarningModal.tsx, apps/desktop/src/setupTests.tsx, apps/web/src/Layout.tsx, apps/web/src/components/SecurityWarningModal/SecurityWarningModal.test.tsx, apps/web/src/components/SecurityWarningModal/SecurityWarningModal.tsx, apps/web/src/components/SocialLoginWarningModal/SocialLoginWarningModal.test.tsx, apps/web/src/components/SocialLoginWarningModal/SocialLoginWarningModal.tsx, packages/components/src/components/DynamicDisclosure/DynamicDisclosure.tsx
This PR adds SocialLoginWarning  to alert user about 2fa importance and implements sequential call to the warning modals
=> Add social login 2fa warning

.github/dependabot.yml
Depndabot spends too many resources.
Will run it monthly on weekends.
=> feat: dependabot to run monthly on weekends

apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx
Adding a backwards compatible change to result for `tezos_send` operation to become compatible with TrustWallet and WalletConnect spec at the same time.
The result of `tezos_send` operation in WalletConnect should look like this according to the spec:
https://docs.reown.com/advanced/multichain/rpc-reference/tezos-rpc
```
"result":  {
"operationHash": "op..."
}
```
But the actual implementation in 3 places returns this:
```
"result":  {
"hash": "op..."
}
```
A `hash` field is returned instead of the `operationHash`.
The implementation returns hash in
* TrustWallet
* Reown's wallet example,, [code](https://github.com/reown-com/web-examples/blob/main/advanced/wallets/react-wallet-v2/src/utils/TezosRequestHandlerUtil.ts#L30)
However, Taquito test dapp follows the spec: …
=> fix: WalletConnect: operationHash and hash for tezos_send

apps/desktop/src/utils/beacon/SignPayloadRequestModal.tsx, apps/web/src/components/beacon/SignPayloadRequestModal.tsx
Fixed error on successful sign request:
`Uncaught (in promise) Error: No matching request found!`
The problem is that on successful sign, `SignPayloadRequestModal` calls `onClose()` which is intended to handle the situation when a user closes the modal window effectively rejecting the request. Since the sign is already approved, an attempt to reject the request results in this error. The logic is the same in web and desktop:
* web: https://github.com/trilitech/umami-v2/blob/main/apps/web/src/components/beacon/useHandleBeaconMessage.tsx#L91
* desktop: https://github.com/trilitech/umami-v2/blob/main/apps/desktop/src/utils/beacon/useHandleBeaconMessage.tsx#L90
The error is not shown after the change.
1. connect wallet with https://taquito-test-dapp.pages.dev/
2. sign payload
3. check the log …
=> fix: Error: No matching request found (on Beacon sign)

apps/web/src/components/beacon/useHandleBeaconMessage.tsx
If a Beacon user closes the modal with Sign Payload request, the conenction is closed and the peer is removed.
This shouldn't happen. It was just a single operation reject.
1. connect umami via Beacon from https://taquito-test-dapp.pages.dev/
2. request to sign payload
3. close the modal
4. check the list of peers
=> fix: beacon was deleting peer on sign close

apps/web/src/components/SendFlow/Beacon/useSignWithBeacon.tsx, apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.tsx, apps/web/src/components/SendFlow/common/Header.tsx, apps/web/src/components/SendFlow/common/OriginationOperationSignPage.test.tsx, apps/web/src/components/SendFlow/common/SingleSignPage.test.tsx, apps/web/src/components/SendFlow/common/SingleSignPage.tsx, apps/web/src/components/SendFlow/common/TezSignPage.test.tsx, apps/web/src/components/SendFlow/utils.tsx, apps/web/src/components/WalletConnect/ProjectInfoCard.tsx, apps/web/src/components/WalletConnect/SessionProposalModal.tsx, apps/web/src/components/WalletConnect/VerifyInfobox.tsx, apps/web/src/components/WalletConnect/useHandleWcRequest.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx, apps/web/src/components/common/SignPayloadRequestModal.test.tsx, apps/web/src/components/common/SignPayloadRequestModal.tsx
Added domain verification for WalletConnect and Beacon.
Beacon has no verification and writes "UNKNOWN" for all domains.
=> feat: WalletConnect integration, part 8, verify

apps/desktop/public/electron.js
This PR handles the case where the data to be extracted is already a valid object, so there is no need to process it again.
=> Fix key extraction during migration

apps/web/src/components/AccountCard/AccountBalance.test.tsx, apps/web/src/components/AccountCard/AccountBalance.tsx, apps/web/src/views/Activity/Activity.test.tsx, apps/web/src/views/Activity/Activity.tsx, apps/web/src/views/Earn/Earn.tsx, apps/web/src/views/Tokens/Token.tsx, apps/web/src/views/Tokens/Tokens.test.tsx, apps/web/src/views/Tokens/Tokens.tsx, packages/state/src/hooks/network.test.ts, packages/state/src/hooks/network.ts
`Buy TEZ` always had mainnet link. Now it uses link for the selected network.
[Task link](https://app.asana.com/0/1207041888417083/1208943913879585/f)
=> [WEB] Fix buy TEZ url

apps/web/src/components/WalletConnect/useHandleWcRequest.tsx, packages/core/src/decodeBeaconPayload.test.ts, packages/core/src/decodeBeaconPayload.ts
Improved payload representation if the `unpackData` fails
Before:
Taquito:
Now:
Test dApp with Tezos Provider
Taquito test dApp
fxhash
objkt
=> feat: detect payload signing type for WalletConnect

apps/web/src/components/Menu/ErrorLogsMenu/ErrorLogsMenu.tsx, apps/web/src/components/WalletConnect/WalletConnectProvider.tsx, apps/web/src/components/WalletConnect/useHandleWcRequest.tsx, packages/data-polling/src/useReactQueryErrorHandler.ts, packages/state/src/hooks/useAsyncActionHandler.ts, packages/state/src/slices/errors.test.ts, packages/test-utils/src/errorContext.ts, packages/utils/src/ErrorContext.test.ts, packages/utils/src/ErrorContext.ts, packages/utils/src/TezosRpcErrors.ts
Significantly improved error handling:
- on user reject, now send the response to the dApp
- handle TezosOperationError: pass data about failure to dApp. Now tests on failure pass in Taquito Test dApp
- provide unique and understandable error text to user (allows to google for the same problem)
- if the error text is parsed, it's provided. If not, the error is more generic. Details are provided since they are unique for the 
contract involved by the user.
The implementation follows:
* https://specs.walletconnect.com/2.0/specs/clients/sign/rpc-methods
* https://www.jsonrpc.org/specification section `5.1 Error object`
1. connect via WalletConnect Taquito Test dApp https://taquito-test-dapp.pages.dev/
2. run tests. All should pass:
```
"Contract call with int",
"Contract call with (pair nat …
```
=> feat: WalletConnect - advanced error handling

apps/desktop-e2e/src/helpers/AccountGroup.ts, packages/utils/package.json, packages/utils/src/ErrorContext.test.ts, packages/utils/src/ErrorContext.ts, pnpm-lock.yaml
Added handling for `HttpErrorResponse`:
- clear error text
- passing clear response to the dApp
- clear info about which url caused the error
DApp gets this error if used with WalletConnect
```
{
"code": 503,
"message": "HTTP request failed for https://rpc.ghostnet.teztnets.com/chains/main/blocks/head/context/constants (503) Service Unavailable - The server is temporarily unable to handle the request. Please try again later or contact support.",
"data": [
503,
"Service Unavailable - The server is temporarily unable to handle the request. Please try again later or contact support.",
"",
"https://rpc.ghostnet.teztnets.com/chains/main/blocks/head/context/constants"
]
}
```
Before:
The only useful message comes for …
=> feat: error handling for HttpErrorResponse

apps/web/src/components/SendFlow/Beacon/useSignWithBeacon.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx, packages/core/src/AccountOperations.ts, packages/core/src/Operation.ts, packages/core/src/beaconUtils.ts, packages/utils/src/ErrorContext.ts
Beacon should handle exceptions and send response to dApp in case of failure.
Asana: [task](https://app.asana.com/0/1205770721172203/1209118741509278)
Details:
Case 1:
- Connect https://taquito-test-dapp.pages.dev/
- Set delegate to some address --> success
- Set delegate to the same address --> toast
- observe the toast "The delegate is unchanged. Delegation to this address is already done."
- the dApp hangs waiting for the response
Case 2:
- connect https://taquito-test-dapp.pages.dev/
- Stake <too much> or 0
- Toast about insufficient balance
- no answer to dApp
Now dApp receives reject:
=> fix: Beacon responds to dApp in case of error

apps/desktop/src/components/SideNavbar.tsx, apps/web/src/components/AccountCard/AccountBalance.test.tsx, apps/web/src/components/AccountCard/AccountBalance.tsx, apps/web/src/components/AccountCard/AccountBalanceDetails.test.tsx, apps/web/src/components/AccountCard/AccountBalanceDetails.tsx, apps/web/src/components/AccountCard/AccountButtons.test.tsx, apps/web/src/components/AccountCard/AccountButtons.tsx, apps/web/src/components/AccountCard/AccountCard.test.tsx, apps/web/src/components/AccountCard/AccountCard.tsx, packages/components/src/components/AddressPill/AddressPillText.tsx, packages/state/src/hooks/assets.test.ts, packages/state/src/hooks/assets.ts, packages/state/src/hooks/staking.ts
[UMA-1037](https://linear.app/tezos/issue/UMA-1037)
Added detailed balance view:
- conversion rate next to the USD balance - always visible
- `Delegated to:` and `Baker name` - shown if delegated
- `Delegation: Inactive` - shown if no delegate and spendable balance is not equal to total balance
- `Spendable:` and value - shown if not equal to the total balance
- `Staked:` and value - shown if not 0
- `Frozen unstaked:` and value - shown if not 0
- `Finalizable:` and value - shown if not 0
The sum of all balance lines is equal to the total balance.
The main principle: the shown information is minimised depending on the account state.
Open main screen.
Play with stake/delegate/unstake
Before:
The view is always the …
=> feat: detailed balance for web, user view

apps/desktop/src/components/SendFlow/Beacon/TezSignPage.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.test.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.tsx, apps/web/src/components/SendFlow/common/ContractCallSignPage.tsx, apps/web/src/components/SendFlow/common/DelegationSignPage.tsx, apps/web/src/components/SendFlow/common/FinalizeUnstakeSignPage.tsx, apps/web/src/components/SendFlow/common/OriginationOperationSignPage.tsx, apps/web/src/components/SendFlow/common/StakeSignPage.tsx, apps/web/src/components/SendFlow/common/TezSignPage.tsx, apps/web/src/components/SendFlow/common/UndelegationSignPage.tsx, apps/web/src/components/SendFlow/common/UnstakeSignPage.tsx, apps/web/src/components/Titles/Titles.tsx, apps/web/src/components/Titles/index.ts
[UMA-1102](https://linear.app/tezos/issue/UMA-1102/walletconnect-bug-header-not-set-for-batch-operation) WalletConnect bug: header not set for batch operation
1. Connect kukai wallet
2. run batch operation
| <img width="445" alt="image" src="https://github.com/user-attachments/assets/7d728438-eaae-4544-b745-131bb9497dbe" /> | <img width="447" alt="image" src="https://github.com/user-attachments/assets/c573c407-c9b1-4634-bc53-ad26f3696766" /> |
=> [Umami mobile][UMA-1102] feat: Batch Request modal header

apps/web/src/components/SendFlow/SuccessStep.tsx, apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx
[UMA-1115](https://linear.app/tezos/issue/UMA-1115)
If the tx confirmation to the WC server failed (e.g. the dApp has disconnected), wallet allows to click Confirm over and over again performing the same operation!
Added exception in packages/state/src/hooks/useAsyncActionHandler.ts:
```
await walletKit.respondSessionRequest({ topic: requestId.topic, response });
throw new CustomError("dApp was not notified test message");
```
| <img width="313" alt="image" src="https://github.com/user-attachments/assets/74bc3a1f-5874-4e26-9d38-fd5a8c8e8f7e" /> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/06248cbd-8076-44b7-be63-c72a85504c6e" /> |
=> [Web][UMA-1115] WC bug: retry on failed notification to dApp

apps/web/src/components/AccountCard/AccountBalance.tsx, apps/web/src/components/AccountCard/AccountCard.tsx, apps/web/src/components/Header/Header.tsx, apps/web/src/components/SendFlow/Beacon/useSignWithBeacon.tsx, apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.test.tsx, apps/web/src/components/SendFlow/common/OriginationOperationSignPage.test.tsx, apps/web/src/components/SendFlow/common/SingleSignPage.test.tsx, apps/web/src/components/SendFlow/common/TezSignPage.test.tsx, apps/web/src/components/SendFlow/utils.tsx, apps/web/src/components/WalletConnect/SessionProposalModal.tsx, apps/web/src/components/WalletConnect/WalletConnectProvider.tsx, apps/web/src/components/beacon/PermissionRequestModal.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.tsx, packages/components/src/components/DynamicDisclosure/DynamicDisclosure.tsx, packages/utils/src/ErrorContext.ts
[UMA-1105](https://linear.app/tezos/issue/UMA-1105/beacon-and-walletconnect-bug-wallet-stops-reacting-on-requests-after) Beacon and WalletConnect bug: wallet stops reacting on requests after dApp connected with open request modal
WalletConnect is queueing the incoming requests. If the request modal gets hidden (e.g. by Beacon request or connection proposal modal), then WalletConnect will wait forever.
FIx: reject new requests (WC or Beacon, session proposals and requests) immediately if any modal is open (except for `SuccessStep`.
Steps for WalletConnect on Umami web:
1. connect https://taquito-test-dapp.pages.dev/
3. confirm on wallet side
4. disconnect from wallet side (to be able to reconnect via a deep link alter on)
5. connect https://wc2.kukai.tech/?network=ghostnet
6. run some …
=> [Web][UMA-1105] WC and Beacon hang on unanswered request

apps/web/src/components/MnemonicWord/MnemonicWord.tsx, apps/web/src/components/Onboarding/ImportWallet/SeedPhraseTab.tsx, apps/web/src/components/Onboarding/VerificationFlow/RecordSeedphraseModal.tsx, apps/web/src/components/Onboarding/VerificationFlow/VerifySeedphraseModal.tsx, apps/web/src/styles/theme.ts, packages/components/src/components/MnemonicAutocomplete/MnemonicAutocomplete.test.tsx, packages/components/src/components/MnemonicAutocomplete/MnemonicAutocomplete.tsx, packages/components/src/hooks/index.ts, packages/components/src/hooks/useToggleMnemonic.test.tsx, packages/components/src/hooks/useToggleMnemonic.tsx
[Task link](https://linear.app/tezos/issue/UMA-1070/add-seed-phrase-account-having-an-eyereveal-per-word-is-not-be-the)
=> [Web] [UMA-1070] Add button to hide whole mnemonic phrase

apps/desktop/.eslintrc.js, apps/web/.eslintrc.cjs, packages/components/.eslintrc.cjs, packages/core/jest.config.ts, packages/core/src/setupTests.ts, packages/data-polling/.eslintrc.cjs, packages/data-polling/jest.config.ts, packages/eslint-config/index.js, packages/multisig/.eslintrc.cjs, packages/multisig/jest.config.ts, packages/multisig/src/setupTests.ts, packages/social-auth/.eslintrc.cjs, packages/state/.eslintrc.cjs, packages/tezos/jest.config.ts, packages/tezos/src/constants.test.ts, packages/tezos/src/constants.ts, packages/tezos/src/setupTests.ts, packages/tzkt/jest.config.ts, packages/tzkt/src/setupTests.ts
[Task link 1](https://linear.app/tezos/issue/UMA-1066/account-card-balance-the-tez-symbol-doesnt-showload-correctly-tested)
[Task link 2](https://linear.app/tezos/issue/UMA-1061/activity-tab-on-iosmobile-the-tez-symbol-doesnt-showload-correctly)
Add XTZ as a fallback for ꜩ on IOS.
=> [Web][UMA-1066] Add fallback for tz symbol on iOS

apps/web/src/components/Onboarding/ImportWallet/ImportBackupTab.tsx
[Task link](https://linear.app/tezos/issue/UMA-1094/add-backup-mobile-when-adding-backup-on-mobile-you-can-scroll-the)
|![image](https://github.com/user-attachments/assets/42f700b3-915c-4b91-b7fb-89df7852b2ae)|<img width="407" alt="image" src="https://github.com/user-attachments/assets/e8456dd6-3c8c-4df0-b7ff-44e2ab100570" />|
=> [Web][UMA-1094] Remove native appearance of import backup input

apps/web/src/components/SendFlow/SuccessStep.test.tsx, apps/web/src/components/SendFlow/SuccessStep.tsx
[UMA-1137](https://linear.app/tezos/issue/UMA-1137/design-notification-to-dapp-failed)
Added exception in apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx:
```
await walletKit.respondSessionRequest({ topic: requestId.topic, response });
throw new CustomError("dApp was not notified test message");
```
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/28ca9581-0588-41c6-9774-ea9ede53a3a7" /> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/dc591bca-9d7c-4c64-bc09-8c586743402c" /> |
=> [Web][UMA-1137] Design for SuccessStep when notification failed

packages/core/src/beaconUtils.ts
[UMA-1123](https://linear.app/tezos/issue/UMA-1123/walletconnect-bug-unsupported-method-is-reported-to-dapp-as)
1. connect Tezos Provider Test dApp [PR#697](https://github.com/WalletConnect/web-examples/pull/697)
2. Run `Increase paid storage`
3. See the reported error
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/c69a8788-0e21-42c2-b0ca-38c7d9e01654" /> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/230c4e32-c99a-4454-ba40-3032a085e11d" /> |
=> [Web][UMA-1123] WalletConnect reports unsupported method correctly

apps/web/src/components/AccountSelectorModal/AccountSelectorModal.test.tsx, apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx, apps/web/src/components/Menu/Menu.test.tsx, apps/web/src/components/Menu/Menu.tsx
- [Remove derive account button for non-mnemonic account groups](https://linear.app/tezos/issue/UMA-1068/account-groupsselector-button-should-probably-only-be-there-for-social)
- [Unify logic for verified & unverified accs](https://linear.app/tezos/issue/UMA-1165/unify-logic-for-verified-and-unverified-accs)
1. Reducing amount of states handled by the wallet:
- states before:
- unverified only (simple menu)
- verified + unverified (menu looks different from verified & unverified accs)
- verified only (full menu)
- states now:
- unverified only (simple menu)
- 1+ verified account (full menu)
2. Adding new accounts is always allowed now
3. Derive account button is removed from non-mnemonic groups
| …
=> [Web][UMA-1068][UMA-1165] Fix Logic for having both - verified & unverified accs

apps/web/src/components/AccountTile/AccountTile.tsx, apps/web/src/components/NameAccountModal/NameAccountModal.test.tsx, apps/web/src/components/NameAccountModal/NameAccountModal.tsx
[UMA-1063](https://linear.app/tezos/issue/UMA-1063/account-card-selector-long-account-name-is-not-cropped) Account Card Selector: Long account name is not cropped
1. create account with very long name
2. login with social account with very long name
3. check account card
4. check account selector modal
| <img width="450" alt="image" src="https://github.com/user-attachments/assets/1a6a4e6a-1438-43f2-a534-b9808354ab25" /> | <img width="450" alt="image" src="https://github.com/user-attachments/assets/19b3fc54-5390-4141-b900-2b8fccb6959d" /> |
| <img width="450" alt="image" src="https://github.com/user-attachments/assets/5ec328ba-dfcd-4f69-be97-98dde5ece729" /> |  <img width="450" …
=> [Web][UMA-1063] Cropped account name for social login

apps/web/src/components/AccountCard/AccountBalanceDetails.test.tsx, apps/web/src/components/AccountCard/AccountBalanceDetails.tsx, apps/web/src/components/AddressPill/AddressPill.tsx, packages/components/src/components/AddressPill/AddressPillText.tsx
[UMA-1157](https://linear.app/tezos/issue/UMA-1157/user-adapt-to-design-present-full-global-stakedunstakedavailable)
Updating baker view on the account card
|        | <img width="450" alt="image" src="https://github.com/user-attachments/assets/1b9ec954-ce64-4770-ae23-6c4adccfc0cd" /> |
|  | <img width="450" alt="image" src="https://github.com/user-attachments/assets/aca751bf-8913-47b8-972e-3758809f9b5a" /> |
=> [Web][UMA-1157] UI: baker name in the account card

apps/web/src/components/HintsAccordion/HintsAccordion.tsx, apps/web/src/components/HintsAccordion/index.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.test.tsx, apps/web/src/components/SendFlow/common/BatchSignPage.tsx, apps/web/src/components/SendFlow/common/ContractCallSignPage.tsx, apps/web/src/components/SendFlow/common/DelegationSignPage.tsx, apps/web/src/components/SendFlow/common/FinalizeUnstakeSignPage.tsx, apps/web/src/components/SendFlow/common/OriginationOperationSignPage.test.tsx, apps/web/src/components/SendFlow/common/OriginationOperationSignPage.tsx, apps/web/src/components/SendFlow/common/SingleSignPage.test.tsx, apps/web/src/components/SendFlow/common/StakeSignPage.tsx, apps/web/src/components/SendFlow/common/TezSignPage.tsx, apps/web/src/components/SendFlow/common/UndelegationSignPage.tsx, apps/web/src/components/SendFlow/common/UnstakeSignPage.tsx, apps/web/src/components/beacon/useHandleBeaconMessage.test.tsx, packages/core/src/constants/Hints.ts, packages/core/src/constants/Titles.tsx, packages/core/src/constants/index.tsx, packages/core/src/index.ts
Umami modals for both Beacon and WalletConnect should be more helpful.
A user can easily make a mistake or hesitate confirming a transaction without understanding of the consequences of the operation.
Task: [UMA-1034](https://linear.app/tezos/issue/UMA-1034)
1. Connect https://taquito-test-dapp.pages.dev/
2. run operations:
- delegate
- undelegate
- stake
- unstake
- finalize
3. see the hint and the details description
Other operations are covered in #2340
| Operation | Before | Now |
| ------ | ------ | --- |
| DelegationRequest | <img width="500" alt="image" src="https://github.com/user-attachments/assets/7dc5ed0b-713b-4f5c-8746-c2489bbc018c" />  | <img width="500" alt="image" …
=> [Web][UMA-1034] hints in modals for Beacon and WC

apps/web/src/components/SendFlow/WalletConnect/useSignWithWalletConnect.tsx, apps/web/src/components/SendFlow/common/SingleSignPage.test.tsx, apps/web/src/components/WalletConnect/SessionProposalModal.tsx, apps/web/src/components/WalletConnect/useHandleWcRequest.tsx, apps/web/src/components/common/SignPayloadRequestModal.test.tsx, apps/web/src/components/common/SignPayloadRequestModal.tsx, packages/state/src/hooks/WalletConnect.test.ts, packages/state/src/hooks/WalletConnect.ts, packages/utils/src/ErrorContext.test.ts, packages/utils/src/ErrorContext.ts
[UMA-1116](https://linear.app/tezos/issue/UMA-1116) Beacon and WalletConnect bug: tx confirmation is allowed after dApp has disconnected
[UMA-1046](https://linear.app/tezos/issue/UMA-1046) WalletConnect bug: wallet allows to confirm an expired request
Request
1. connect dapp, e.g. https://taquito-test-dapp.pages.dev/
2. send request, e.g. send tez
3. wait till the modal opens on wallet; then disconnect dApp
4. try to reject or confirm the operation
Session proposal:
1. connect dapp, e.g. https://taquito-test-dapp.pages.dev/
2. wait till the modal opens on wallet; then disconnect dApp; open the QR code again
4. try to reject or confirm the session proposal
Another way to reproduce is wait for 5 minutes to make sure the request/proposal has expired.
Add the screenshots of how the app used …
=> [Web][UMA-1116][UMA-1046] WallectConnect validates proposals and requests

apps/web/src/components/AccountCard/AccountBalanceDetails.tsx
[UMA-1186](https://linear.app/tezos/issue/UMA-1186/design-delegation-tag-too-narrow-on-web-wider-than-775px) Design: delegation tag too narrow on web wider than 775px
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/bd75da2e-32bb-4165-bf49-e48f546a2335" />|  <img width="400" alt="image" src="https://github.com/user-attachments/assets/64ea71e2-f1ca-4095-9ed5-2fdf67e445fb" /> |
| Width | Now |
| -- | -- |
|  iPhone SE, w375 | <img width="450" alt="image" src="https://github.com/user-attachments/assets/322a8475-addf-4bf7-addc-e71c0b6388be" /> |
| iPhone 14 Pro Max, w430 | <img width="450" alt="image" …
=> [Web][UMA-1186] Delegation tag width

apps/web/src/components/Onboarding/VerificationFlow/RecordSeedphraseModal.tsx, apps/web/src/components/Onboarding/VerificationFlow/VerifySeedphraseModal.tsx
[UMA-1048](https://linear.app/tezos/issue/UMA-1048/verify-your-account-on-mobile-i-suggest-showing-the-seed-phrase) Verify your account: On mobile, I suggest showing the seed phrase verification fields in 3 separate rows instead of 1 row with 3 columns.
| Case | Before | Now |
| -- | ------ | --- |
| laptop | <img width="350" alt="image" src="https://github.com/user-attachments/assets/cb8b0e2f-3b72-490e-b34c-add9f0dcd832" /> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/988fe7e8-73bf-4c5b-894c-cac815fe7f47" /> |
| mobile | <img width="350" alt="image" src="https://github.com/user-attachments/assets/aeba56f3-42c4-46e9-84cc-6949f8fb44da" /> | <img width="350" alt="image" …
=> [Web][UMA-1048] Column words in verify on mobile

apps/web/src/components/AccountSelectorModal/AccountSelectorModal.test.tsx, apps/web/src/components/AccountSelectorModal/AccountSelectorModal.tsx, apps/web/src/components/AccountSelectorModal/RemoveAccountModal.test.tsx, apps/web/src/components/AccountSelectorModal/RemoveAccountModal.tsx, apps/web/src/components/Menu/LogoutModal.test.tsx, apps/web/src/components/Menu/LogoutModal.tsx, packages/state/src/beacon/WalletClient.ts, packages/state/src/hooks/getAccountData.ts
[Task link](https://linear.app/tezos/issue/UMA-1191/fix-remove-account)
Add two accounts, and remove the default one. Then close the tab and open a new tab, it asks for password and after entering the password it says mnemonic could not be found.
|     
|     |
Added a test which checks that localstorage.clear is called after deleting the default account which would fix all the issues related to removal of default account. 
Also added a test which tests the copy shown while trying to delete the default account. It should warn the users that deleting default account will delete their umami account from that device.
=> [Web][UMA-1191] Disable removal of default account

apps/web/src/views/NFTs/NFTDrawerCard/NFTDrawerCard.tsx
[UMA-1058](https://linear.app/tezos/issue/UMA-1058/nfts-drawer-on-mobile-when-i-tap-on-a-video-nft-it-opens-up-the-video) NFTs Drawer on Mobile: When I tap on a video NFT, it opens up the video on my screen instead of showing me the drawer. When I close the video, then I can see the drawer.
1. buy NFT https://ghostnet.objkt.com/tokens/KT1H2Ag5DyTxNWH4KAntHGX5WVS1ggZUoPUE/0
2. open NFT 
- on laptop
- on real mobile
See vercel.
=> [Web][UMA-1058][UMA-1245] NFTs video not in drawer

apps/web/src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.test.tsx, apps/web/src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.tsx
[Task link](https://linear.app/tezos/issue/UMA-1247/your-new-passwords-do-not-match-error-after-the-new-password-was)
1. advanced -> change password
2. set new password 
3. set confirmation password different -> see error `Your new passwords do not match`
4. fix new password to match -> no error
5. change new password to different -> see error `Your new passwords do not match`
```
pnpm test src/components/Menu/ChangePasswordMenu/ChangePasswordMenu.test.tsx
```
=> [Web][UMA-1247] Check confirmed password on password change

apps/web/src/components/AddressPill/AddressPill.tsx, apps/web/src/components/Menu/AppsMenu/GenericConnections.tsx
[Task link](https://linear.app/tezos/issue/UMA-1243/corrupted-dapps-list-if-account-name-is-very-long)
a) Connect a dApps to an Account with a long name
or
b) make your chrome window width very narrow 
|
|  
- no test were added as this is just a css style change
=> [WEB][UMA-1243] Trims too long dApps account name

apps/web/src/components/AccountCard/AccountCard.tsx, packages/components/src/components/DynamicDisclosure/DynamicDisclosure.tsx
[Task link](https://linear.app/tezos/issue/UMA-1067/account-selector-users-can-only-close-the-modals-by-using-the-close)
1) Login into the wallet
2) Click on the arrows near your account 
3) The modal pop up
4) Now click on the blurred overlay to see the modal disappear
- test were not possible to be written as the chakra-ui modal used is probably not using the normal listener for click events on the overlay or any other modal-related items
=> [Web][UMA-1067] Account selection modal is closed when the modal overlay is clicked
